//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHeartA
    {
        public decimal AHeartAID { get; set; }
        public decimal AHASisMax { get; set; }
        public decimal AHADiastMax { get; set; }
        public string AHAKategoria { get; set; }
        public string AHAPreporaki { get; set; }
    }
}
