//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertInfo
    {
        public decimal AlertID { get; set; }
        public decimal AlertPacID { get; set; }
        public System.DateTime AlertData { get; set; }
        public string AlertAlerg { get; set; }
        public string AlertProt { get; set; }
        public string AlertZab { get; set; }
        public string AlertDrugi { get; set; }
        public Nullable<decimal> AlertPregledID { get; set; }
        public Nullable<decimal> AlertBolID { get; set; }
    
        public virtual Pacient Pacient { get; set; }
    }
}
