//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbList2005
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmbList2005()
        {
            this.DoctorCommissionProtocol = new HashSet<DoctorCommissionProtocol>();
            this.BList1 = new HashSet<BList>();
            this.AmbList2005Med = new HashSet<AmbList2005Med>();
            this.NOIProverka = new HashSet<NOIProverka>();
            this.Recepta = new HashSet<Recepta>();
        }
    
        public decimal AmbListID { get; set; }
        public Nullable<decimal> PacientID { get; set; }
        public Nullable<decimal> LekarID { get; set; }
        public Nullable<decimal> LZID { get; set; }
        public Nullable<decimal> PregledID { get; set; }
        public Nullable<decimal> ProID { get; set; }
        public Nullable<decimal> DiiID { get; set; }
        public Nullable<decimal> EfiID { get; set; }
        public Nullable<decimal> IpID { get; set; }
        public Nullable<decimal> RodID { get; set; }
        public Nullable<decimal> FniID { get; set; }
        public bool IsValid { get; set; }
        public bool IsOthvurlen { get; set; }
        public Nullable<decimal> AmbListKamOtchet { get; set; }
        public decimal AmbListNo { get; set; }
        public System.DateTime Datata { get; set; }
        public string SimpAmbNo { get; set; }
        public Nullable<System.DateTime> SimpData { get; set; }
        public bool Consult { get; set; }
        public bool Profilact { get; set; }
        public Nullable<bool> DZ { get; set; }
        public Nullable<bool> MZ { get; set; }
        public Nullable<bool> Z18 { get; set; }
        public string GestWeek { get; set; }
        public Nullable<bool> RiskGroup { get; set; }
        public bool Disp { get; set; }
        public bool VSD { get; set; }
        public Nullable<bool> VSDBol { get; set; }
        public bool RpHosp { get; set; }
        public bool Expertiza { get; set; }
        public bool PoTELK { get; set; }
        public bool PregledAmb { get; set; }
        public bool AmbParv { get; set; }
        public bool AmbVtor { get; set; }
        public bool PregledDom { get; set; }
        public bool DomParv { get; set; }
        public bool DomVtor { get; set; }
        public string ImunKod1 { get; set; }
        public string ImunKod2 { get; set; }
        public string ImunKod3 { get; set; }
        public string MantuKod { get; set; }
        public bool TalonLKK { get; set; }
        public string TalonLKKNo { get; set; }
        public bool Hospitaliz { get; set; }
        public bool BList { get; set; }
        public string BListNo { get; set; }
        public Nullable<decimal> BListDiag { get; set; }
        public Nullable<short> BListDni { get; set; }
        public Nullable<System.DateTime> BListOtData { get; set; }
        public Nullable<System.DateTime> BListDoData { get; set; }
        public Nullable<bool> BListParv { get; set; }
        public string RpType { get; set; }
        public string RpBook { get; set; }
        public bool Izvestie { get; set; }
        public bool EtEpikriza { get; set; }
        public bool Podpis { get; set; }
        public Nullable<decimal> MainDiag1 { get; set; }
        public Nullable<decimal> MainDiag2 { get; set; }
        public Nullable<decimal> DopDiag1 { get; set; }
        public Nullable<decimal> DopDiag2 { get; set; }
        public Nullable<decimal> DopDiag3 { get; set; }
        public Nullable<decimal> DopDiag4 { get; set; }
        public Nullable<decimal> DopDiag5 { get; set; }
        public Nullable<decimal> DopDiag6 { get; set; }
        public Nullable<decimal> DopDiag7 { get; set; }
        public Nullable<decimal> DopDiag8 { get; set; }
        public string Anamnesa { get; set; }
        public string HState { get; set; }
        public string Examine { get; set; }
        public string Therapy { get; set; }
        public Nullable<decimal> Procedura1 { get; set; }
        public string Procedura1Kod { get; set; }
        public string Procedura1Text { get; set; }
        public Nullable<decimal> Procedura2 { get; set; }
        public string Procedura2Kod { get; set; }
        public string Procedura2Text { get; set; }
        public Nullable<decimal> Procedura3 { get; set; }
        public string Procedura3Kod { get; set; }
        public string Procedura3Text { get; set; }
        public Nullable<bool> NeblUslovia { get; set; }
        public string Procedura4Kod { get; set; }
        public string Procedura4Text { get; set; }
        public string SpecLekar { get; set; }
        public Nullable<decimal> LekarIDKod { get; set; }
        public Nullable<bool> ZamLekar { get; set; }
        public Nullable<bool> NaetLekar { get; set; }
        public string UINZamNaet { get; set; }
        public Nullable<bool> PotrTaksa { get; set; }
        public bool AmbMZDisp { get; set; }
        public Nullable<decimal> DoctorCommissionId { get; set; }
        public bool BezNapr3 { get; set; }
        public bool IzborDisp { get; set; }
        public bool PMS17 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorCommissionProtocol> DoctorCommissionProtocol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BList> BList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmbList2005Med> AmbList2005Med { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIProverka> NOIProverka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepta> Recepta { get; set; }
    }
}
