//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbList2005Med
    {
        public decimal ALMId { get; set; }
        public decimal AmbListID { get; set; }
        public string ALMCode { get; set; }
        public decimal ALMKol { get; set; }
        public Nullable<decimal> ALMDni { get; set; }
        public Nullable<decimal> ALMRecNo { get; set; }
    
        public virtual AmbList2005 AmbList2005 { get; set; }
    }
}
