//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anestezia
    {
        public decimal AnesteziaID { get; set; }
        public Nullable<decimal> OperaciaID { get; set; }
        public Nullable<decimal> PacientID { get; set; }
        public System.DateTime AnesNachalo { get; set; }
        public System.DateTime AnesKrai { get; set; }
        public string AnesProtokol { get; set; }
        public decimal AnesVid { get; set; }
        public string AnesObshti { get; set; }
        public string AnesPremed { get; set; }
        public string AnesUvod { get; set; }
        public string AnesDiureza { get; set; }
        public string AnesFinalni { get; set; }
        public decimal AnesLekar { get; set; }
        public Nullable<decimal> AnesSestra { get; set; }
        public string AnesProt { get; set; }
        public Nullable<decimal> DiiID { get; set; }
        public Nullable<decimal> IpID { get; set; }
        public Nullable<decimal> EfiID { get; set; }
        public Nullable<decimal> ProID { get; set; }
    
        public virtual IzsDI IzsDI { get; set; }
        public virtual IzsEFI IzsEFI { get; set; }
        public virtual IzsIP IzsIP { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Operacia Operacia { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Personal Personal1 { get; set; }
    }
}
