//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUView
    {
        public decimal UslugaID { get; set; }
        public string UslugaKod { get; set; }
        public string UslugaIme { get; set; }
        public System.DateTime UslugaDoData { get; set; }
        public Nullable<bool> UslugaIsDogovor { get; set; }
        public System.DateTime DogNzokDataOt { get; set; }
        public System.DateTime DogNzokDataDo { get; set; }
        public decimal KumOtcheta { get; set; }
    }
}
