//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class blxml
    {
        public decimal boListID { get; set; }
        public string PatientsChartNumber { get; set; }
        public string CodeOperation { get; set; }
        public int PatientsChartType { get; set; }
        public string NumberOfMedicalCard { get; set; }
        public string NumberOfMedicalExam { get; set; }
        public string NumberInHospital { get; set; }
        public string LKKTypeCode { get; set; }
        public string LKKTypeText { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string FamilyName { get; set; }
        public string EGN { get; set; }
        public int FlagEGN { get; set; }
        public string EGNAge { get; set; }
        public string Sex { get; set; }
        public string PatientsAddressCity { get; set; }
        public string PatientsAddress { get; set; }
        public Nullable<decimal> RZINomer { get; set; }
        public string MedicalInstitutionName { get; set; }
        public string ClientBULSTAT { get; set; }
        public string InsurerName { get; set; }
        public string InsurerAddressCity { get; set; }
        public string InsurerAddress { get; set; }
        public string Profession { get; set; }
        public string Position { get; set; }
        public Nullable<int> SickLeaveStartDate_Day { get; set; }
        public Nullable<int> SickLeaveStartDate_Month { get; set; }
        public Nullable<int> SickLeaveStartDate_Year { get; set; }
        public Nullable<int> SickLeaveEndDate_Day { get; set; }
        public Nullable<int> SickLeaveEndDate_Month { get; set; }
        public Nullable<int> SickLeaveEndDate_Year { get; set; }
        public decimal SickLeaveLegalDays { get; set; }
        public string SickLeaveLegalDaysWords { get; set; }
        public string DiagnosisCode { get; set; }
        public string DiagnosisName { get; set; }
        public string ReasonOfDiseaseCode { get; set; }
        public string ReasonOfDiseaseName { get; set; }
        public string MedicalInstitutionAddressObl { get; set; }
        public string MedicalInstitutionAddress { get; set; }
        public string MedicalInstitutionAddressCity { get; set; }
        public string PregnancyTermDate_Day { get; set; }
        public string PregnancyTermDate_Month { get; set; }
        public string PregnancyTermDate_Year { get; set; }
        public string PregnancyDeliveryDate_Day { get; set; }
        public string PregnancyDeliveryDate_Month { get; set; }
        public string PregnancyDeliveryDate_Year { get; set; }
        public string TypeSickCode { get; set; }
        public string TypeSickName { get; set; }
        public string NamesSick_FirstName { get; set; }
        public string NamesSick_SurName { get; set; }
        public string NamesSick_FamilyName { get; set; }
        public string EGNSick { get; set; }
        public string FlagEGNSick { get; set; }
        public string LKKDecisionNumber { get; set; }
        public string LKKDecisionDateDay { get; set; }
        public string LKKDecisionDateMonth { get; set; }
        public string LKKDecisionDateYear { get; set; }
        public string TELKDecisionNumber { get; set; }
        public string TELKDecisionDateDay { get; set; }
        public string TELKDecisionDateMonth { get; set; }
        public string TELKDecisionDateYear { get; set; }
        public string CodeNote { get; set; }
        public string TextNote { get; set; }
        public string AdditionalNote { get; set; }
        public Nullable<int> PatientsChartIssuedBy { get; set; }
        public string FamilyNameDoctor1 { get; set; }
        public string UIN1 { get; set; }
        public string FamilyNameDoctor2 { get; set; }
        public string UIN2 { get; set; }
        public string FamilyNameDoctor3 { get; set; }
        public string UIN3 { get; set; }
        public Nullable<int> DateIssuedDay { get; set; }
        public Nullable<int> DateIssuedMonth { get; set; }
        public Nullable<int> DateIssuedYear { get; set; }
        public string DeletedPCNumber { get; set; }
        public string DeletedRegMedInsNumber { get; set; }
        public string ReasonForDelete { get; set; }
        public string ReasonForDeleteCode { get; set; }
        public string ClientEGN { get; set; }
        public string MedicalInstitutionType { get; set; }
    }
}
