//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLXMLTZ
    {
        public decimal boListID { get; set; }
        public Nullable<decimal> kind { get; set; }
        public Nullable<int> sumgroup { get; set; }
        public Nullable<decimal> days { get; set; }
    }
}
