//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolnichnoLechenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BolnichnoLechenie()
        {
            this.BList = new HashSet<BList>();
            this.BLOcenki = new HashSet<BLOcenki>();
            this.toCypro = new HashSet<toCypro>();
            this.EjNaznachenie = new HashSet<EjNaznachenie>();
            this.IntLechenie = new HashSet<IntLechenie>();
            this.IzsDI = new HashSet<IzsDI>();
            this.IzsEFI = new HashSet<IzsEFI>();
            this.IzsFNI = new HashSet<IzsFNI>();
            this.IzsIP = new HashSet<IzsIP>();
            this.IzsLAB = new HashSet<IzsLAB>();
            this.IzsROD = new HashSet<IzsROD>();
            this.IzsVSI = new HashSet<IzsVSI>();
            this.Konsultacia = new HashSet<Konsultacia>();
            this.MartvoRodeni = new HashSet<MartvoRodeni>();
            this.MedTerapia = new HashSet<MedTerapia>();
            this.NOIProverka = new HashSet<NOIProverka>();
            this.NOIProverka1 = new HashSet<NOIProverka>();
            this.NovoRodeni = new HashSet<NovoRodeni>();
            this.Operacia = new HashSet<Operacia>();
            this.OrderEntry = new HashSet<OrderEntry>();
            this.Pochinali = new HashSet<Pochinali>();
            this.Pregled = new HashSet<Pregled>();
            this.Prevejdane = new HashSet<Prevejdane>();
            this.Pridrujitel = new HashSet<Pridrujitel>();
            this.Razhod_Transfer = new HashSet<Razhod_Transfer>();
            this.TabelaMedi = new HashSet<TabelaMedi>();
        }
    
        public decimal ID { get; set; }
        public decimal BLPacID { get; set; }
        public string BLIZNo { get; set; }
        public Nullable<decimal> BLNasOt { get; set; }
        public string BLNasDok { get; set; }
        public Nullable<bool> BLHasDogNZOK { get; set; }
        public Nullable<decimal> BLNasRZOKNo { get; set; }
        public Nullable<decimal> BLNasZdrRaion { get; set; }
        public Nullable<decimal> BLNasZavRegNo { get; set; }
        public string BLNasEGNLekar { get; set; }
        public string BLNasLekarIme { get; set; }
        public Nullable<bool> BLNasIsSpeshen { get; set; }
        public string BLNasKliPat { get; set; }
        public Nullable<decimal> BLNasDiag1 { get; set; }
        public Nullable<decimal> BLNasDiagDop1 { get; set; }
        public Nullable<decimal> BLNasDiag2 { get; set; }
        public Nullable<decimal> BLNasDiagDop2 { get; set; }
        public Nullable<System.DateTime> BLDatIzprashtane { get; set; }
        public string BLNasMedDok { get; set; }
        public string BLNasMedRez { get; set; }
        public string BLNasBelejki { get; set; }
        public System.DateTime BLDataChas { get; set; }
        public decimal BLOtdelenie { get; set; }
        public string BLStaia { get; set; }
        public string BLLeglo { get; set; }
        public Nullable<bool> BLIsVIP { get; set; }
        public System.DateTime BLDatIzpisvane { get; set; }
        public decimal BLVidPac { get; set; }
        public Nullable<bool> BLIsSpeshen { get; set; }
        public Nullable<decimal> BLKliPat { get; set; }
        public Nullable<decimal> BLLekarID { get; set; }
        public decimal BLDiag1 { get; set; }
        public Nullable<decimal> BLDiagDop1 { get; set; }
        public Nullable<decimal> BLDiag2 { get; set; }
        public Nullable<decimal> BLDiagDop2 { get; set; }
        public Nullable<System.DateTime> BlParviPregled { get; set; }
        public Nullable<System.DateTime> BlPlPriem { get; set; }
        public decimal BLFinansirane { get; set; }
        public string BLStepenTej { get; set; }
        public Nullable<bool> BLPrevejdane { get; set; }
        public Nullable<decimal> BLVremeOtNach { get; set; }
        public Nullable<decimal> BLPrichina { get; set; }
        public Nullable<bool> BLIsDenem { get; set; }
        public Nullable<decimal> BLAvansPla { get; set; }
        public Nullable<decimal> BLKruvBroi { get; set; }
        public string BLDruDanni { get; set; }
        public Nullable<decimal> BLPlanID { get; set; }
        public Nullable<bool> BLHasPrestoi { get; set; }
        public Nullable<bool> BLIsNapusnal { get; set; }
        public Nullable<System.DateTime> BLNapDataChas { get; set; }
        public Nullable<decimal> BLNapKliPat { get; set; }
        public Nullable<short> BLNapDetDni { get; set; }
        public Nullable<short> BLNapDetGram { get; set; }
        public Nullable<int> BLNapMamIZN { get; set; }
        public Nullable<short> BLNapMamGod { get; set; }
        public Nullable<decimal> BLNapOkDiag { get; set; }
        public Nullable<decimal> BLNapOkDiagDop { get; set; }
        public Nullable<decimal> BLNapDopDiag1 { get; set; }
        public Nullable<decimal> BLNapDopDiag2 { get; set; }
        public Nullable<decimal> BLNapDopDiag3 { get; set; }
        public Nullable<decimal> BLNapDopDiag4 { get; set; }
        public Nullable<decimal> BLNapDopDiag5 { get; set; }
        public Nullable<decimal> BLNapUslojnenie { get; set; }
        public Nullable<decimal> BLNapStatus { get; set; }
        public Nullable<decimal> BLNapIzpisan { get; set; }
        public Nullable<bool> BLNapOtkazal { get; set; }
        public string BLNapOtkPrichina { get; set; }
        public Nullable<decimal> BLNapPreBolnica { get; set; }
        public Nullable<decimal> BLNapPreDiag { get; set; }
        public Nullable<decimal> BLNapPreDiagDop { get; set; }
        public Nullable<decimal> BLNapSustoianie { get; set; }
        public Nullable<bool> BLNapPodMinPrestoi { get; set; }
        public Nullable<bool> BLPovHos { get; set; }
        public Nullable<decimal> BLNapNasochen { get; set; }
        public Nullable<decimal> BLNapNeoperirane { get; set; }
        public Nullable<bool> BLNapInfekcia { get; set; }
        public Nullable<decimal> BLNapLekar { get; set; }
        public Nullable<decimal> BLNapZavLekar { get; set; }
        public string BLNapFinDanni { get; set; }
        public string BLNapOkDiagDrugi { get; set; }
        public string BLNapDiag1Drugi { get; set; }
        public string BLNapDiag2Drugi { get; set; }
        public string BLNapUslojDrugi { get; set; }
        public Nullable<bool> BLDopZof { get; set; }
        public string BLStatus { get; set; }
        public string BLAnamneza { get; set; }
        public string Protocol { get; set; }
        public Nullable<decimal> BLNapOtdel { get; set; }
        public string BLNapPrePrich { get; set; }
        public Nullable<bool> BLVarnatOtOtch { get; set; }
        public string BLPrichVarnat { get; set; }
        public Nullable<decimal> BLRazMed { get; set; }
        public Nullable<decimal> BLRazKon { get; set; }
        public Nullable<decimal> BLNasPers { get; set; }
        public Nullable<System.DateTime> BlNapDTHist { get; set; }
        public Nullable<short> BlNapDetTeglo { get; set; }
        public Nullable<bool> BlProveren { get; set; }
        public Nullable<bool> BlOtdOtchet { get; set; }
        public string BlPOEpikriza { get; set; }
        public string BlInfoSaglasie { get; set; }
        public Nullable<System.DateTime> BlNapISData { get; set; }
        public string BlProtEN { get; set; }
        public string BlDeclIS { get; set; }
        public string BlDeclZO { get; set; }
        public string BlDeclOKP { get; set; }
        public string BlRP { get; set; }
        public string BlRecepta { get; set; }
        public string BlFish34 { get; set; }
        public string BlEtEpikriza { get; set; }
        public string BlPodEpikriz { get; set; }
        public string BlFishDehosp { get; set; }
        public string BlDeclKrav { get; set; }
        public Nullable<decimal> BlHistRes { get; set; }
        public string BlHistResDop { get; set; }
        public string BlZaiavIL { get; set; }
        public Nullable<decimal> BlLekLekar { get; set; }
        public Nullable<decimal> BlHistIzsledvane { get; set; }
        public string BlUINZam { get; set; }
        public Nullable<decimal> BlSpecLekar { get; set; }
        public Nullable<int> oldPraktikaId { get; set; }
        public Nullable<int> DietID { get; set; }
        public bool BlKplsEarly { get; set; }
        public bool IsBlNasAPr { get; set; }
        public string BLRedirectedAPr { get; set; }
        public Nullable<int> BLNapSubOtdel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BList> BList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOcenki> BLOcenki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toCypro> toCypro { get; set; }
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Diagnoza Diagnoza1 { get; set; }
        public virtual Diagnoza Diagnoza2 { get; set; }
        public virtual Diagnoza Diagnoza3 { get; set; }
        public virtual Diagnoza Diagnoza4 { get; set; }
        public virtual Diagnoza Diagnoza5 { get; set; }
        public virtual Diagnoza Diagnoza6 { get; set; }
        public virtual Diagnoza Diagnoza7 { get; set; }
        public virtual Diagnoza Diagnoza8 { get; set; }
        public virtual Diet Diet { get; set; }
        public virtual KlinicnaPateka KlinicnaPateka { get; set; }
        public virtual KlinicnaPateka KlinicnaPateka1 { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Nomenklatura Nomenklatura2 { get; set; }
        public virtual Nomenklatura Nomenklatura3 { get; set; }
        public virtual Nomenklatura Nomenklatura4 { get; set; }
        public virtual Nomenklatura Nomenklatura5 { get; set; }
        public virtual Nomenklatura Nomenklatura6 { get; set; }
        public virtual Nomenklatura Nomenklatura7 { get; set; }
        public virtual Nomenklatura Nomenklatura8 { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Personal Personal1 { get; set; }
        public virtual Personal Personal2 { get; set; }
        public virtual Personal Personal3 { get; set; }
        public virtual PlaniranePregled PlaniranePregled { get; set; }
        public virtual SubZveno SubZveno { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Zveno Zveno1 { get; set; }
        public virtual BolnichnoLechenieDop BolnichnoLechenieDop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EjNaznachenie> EjNaznachenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntLechenie> IntLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsDI> IzsDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsEFI> IzsEFI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsFNI> IzsFNI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsIP> IzsIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsLAB> IzsLAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsROD> IzsROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsVSI> IzsVSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konsultacia> Konsultacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MartvoRodeni> MartvoRodeni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedTerapia> MedTerapia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIProverka> NOIProverka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIProverka> NOIProverka1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NovoRodeni> NovoRodeni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacia> Operacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEntry> OrderEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pochinali> Pochinali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregled> Pregled { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prevejdane> Prevejdane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pridrujitel> Pridrujitel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Razhod_Transfer> Razhod_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelaMedi> TabelaMedi { get; set; }
    }
}
