//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broiach
    {
        public decimal BroiachID { get; set; }
        public decimal BroiachGodina { get; set; }
        public decimal BroiachJurnalenNomer { get; set; }
        public decimal BroiachArhivenNomer { get; set; }
        public decimal BroiachIzNomer { get; set; }
        public decimal BroiachAmbNomer { get; set; }
        public decimal BroiachNazn { get; set; }
        public decimal BroiachSpeshni { get; set; }
        public decimal BroiachDispList { get; set; }
        public decimal BroiachTabelaMedi { get; set; }
        public decimal BroiachKPr { get; set; }
        public decimal BroiachPrescrNumber { get; set; }
        public decimal BroiachPlanCounter { get; set; }
        public decimal BroiachAPr38DecisionNumber { get; set; }
    }
}
