//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cena
    {
        public decimal CenaID { get; set; }
        public decimal UslugaID { get; set; }
        public Nullable<decimal> CenaBg { get; set; }
        public Nullable<decimal> CenaNotBg { get; set; }
        public Nullable<decimal> CenaNZOK { get; set; }
        public System.DateTime CenaData { get; set; }
        public Nullable<decimal> CenaDogovor { get; set; }
        public Nullable<decimal> CenaDeinost { get; set; }
        public Nullable<decimal> MedCentar { get; set; }
    
        public virtual Usluga Usluga { get; set; }
    }
}
