//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeniNZOKAmb
    {
        public decimal CNId { get; set; }
        public string CNKod { get; set; }
        public string CNIme { get; set; }
        public decimal CNCena { get; set; }
        public System.DateTime CNData { get; set; }
        public string CNRes { get; set; }
    }
}
