//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebugITAnalysis
    {
        public int ID { get; set; }
        public string ATCCode { get; set; }
        public string Url { get; set; }
        public string Uri { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
