//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeinostNZOK
    {
        public decimal DeinostNzokID { get; set; }
        public decimal DogovorNzokID { get; set; }
        public decimal DeinostVid { get; set; }
    
        public virtual DogovorNZOK DogovorNZOK { get; set; }
    }
}
