//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnozaSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiagnozaSpec()
        {
            this.DiagnozaSpec1 = new HashSet<DiagnozaSpec>();
        }
    
        public decimal DiagnozaSpecID { get; set; }
        public Nullable<decimal> DiagnozaSpecSelfID { get; set; }
        public string DiagnozaSpecIme { get; set; }
        public string DiagnozaSpecKod { get; set; }
        public string DiagnozaSpecOpisanie { get; set; }
        public Nullable<decimal> DiagnozaSpecSort { get; set; }
        public string DiagnozaSpecZabelejka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnozaSpec> DiagnozaSpec1 { get; set; }
        public virtual DiagnozaSpec DiagnozaSpec2 { get; set; }
    }
}
