//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnoza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnoza()
        {
            this.BList = new HashSet<BList>();
            this.BolnichnoLechenie = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie1 = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie2 = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie3 = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie4 = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie5 = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie6 = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie7 = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie8 = new HashSet<BolnichnoLechenie>();
            this.DiagKlinPateka = new HashSet<DiagKlinPateka>();
            this.PregnancyRegister = new HashSet<PregnancyRegister>();
            this.KpLechenie = new HashSet<KpLechenie>();
            this.Diagnoza1 = new HashSet<Diagnoza>();
            this.DiagUslojnPridr = new HashSet<DiagUslojnPridr>();
            this.DiagUslojnPridr1 = new HashSet<DiagUslojnPridr>();
            this.IzsDI = new HashSet<IzsDI>();
            this.IzsDI1 = new HashSet<IzsDI>();
            this.IzsEFI = new HashSet<IzsEFI>();
            this.IzsEFI1 = new HashSet<IzsEFI>();
            this.IzsFNI = new HashSet<IzsFNI>();
            this.IzsFNI1 = new HashSet<IzsFNI>();
            this.IzsIP = new HashSet<IzsIP>();
            this.IzsIP1 = new HashSet<IzsIP>();
            this.IzsLAB = new HashSet<IzsLAB>();
            this.IzsROD = new HashSet<IzsROD>();
            this.IzsVSI = new HashSet<IzsVSI>();
            this.IzsVSI1 = new HashSet<IzsVSI>();
            this.Konsultacia = new HashSet<Konsultacia>();
            this.Operacia = new HashSet<Operacia>();
            this.Operacia1 = new HashSet<Operacia>();
            this.Operacia2 = new HashSet<Operacia>();
            this.Operacia3 = new HashSet<Operacia>();
            this.Operacia4 = new HashSet<Operacia>();
            this.Operacia5 = new HashSet<Operacia>();
            this.Pochinali = new HashSet<Pochinali>();
            this.Pochinali1 = new HashSet<Pochinali>();
            this.Pregled = new HashSet<Pregled>();
            this.PregledDiagnoza = new HashSet<PregledDiagnoza>();
            this.RazhodTipActivities = new HashSet<RazhodTipActivities>();
            this.Proceduri = new HashSet<Proceduri>();
            this.Proceduri1 = new HashSet<Proceduri>();
            this.Pochinali2 = new HashSet<Pochinali>();
        }
    
        public decimal DiagnozaID { get; set; }
        public Nullable<decimal> DiagnozaSelfID { get; set; }
        public string DiagIme { get; set; }
        public string DiagKod { get; set; }
        public string DiagOpis { get; set; }
        public string DiagSadarja { get; set; }
        public string DiagNeSadarja { get; set; }
        public string DiagZabelejka { get; set; }
        public Nullable<decimal> DiagSort { get; set; }
        public Nullable<bool> DiagIsInvisible { get; set; }
        public Nullable<bool> DiagIsDiag { get; set; }
        public Nullable<bool> DiagIsMKB10 { get; set; }
        public Nullable<bool> DiagIsFav { get; set; }
        public Nullable<bool> DiagIsZvezda { get; set; }
        public Nullable<bool> DiagZaMaje { get; set; }
        public Nullable<bool> DiagZaJeni { get; set; }
        public Nullable<bool> DiagZaDeca { get; set; }
        public Nullable<bool> DiagZaVazrastni { get; set; }
        public Nullable<bool> DiagNeZaSmart { get; set; }
        public Nullable<bool> DiagIsSpec { get; set; }
        public bool IsAKMP { get; set; }
        public string MkbAkmpMapping { get; set; }
        public string CodingAlso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BList> BList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagKlinPateka> DiagKlinPateka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PregnancyRegister> PregnancyRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KpLechenie> KpLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnoza> Diagnoza1 { get; set; }
        public virtual Diagnoza Diagnoza2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagUslojnPridr> DiagUslojnPridr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagUslojnPridr> DiagUslojnPridr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsDI> IzsDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsDI> IzsDI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsEFI> IzsEFI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsEFI> IzsEFI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsFNI> IzsFNI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsFNI> IzsFNI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsIP> IzsIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsIP> IzsIP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsLAB> IzsLAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsROD> IzsROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsVSI> IzsVSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsVSI> IzsVSI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konsultacia> Konsultacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacia> Operacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacia> Operacia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacia> Operacia2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacia> Operacia3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacia> Operacia4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacia> Operacia5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pochinali> Pochinali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pochinali> Pochinali1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregled> Pregled { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PregledDiagnoza> PregledDiagnoza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RazhodTipActivities> RazhodTipActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proceduri> Proceduri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proceduri> Proceduri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pochinali> Pochinali2 { get; set; }
    }
}
