//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diag_KDKK
    {
        public decimal DK_Id { get; set; }
        public string AEPC_Code { get; set; }
        public string MKB9_Code { get; set; }
        public decimal MKB9_Id { get; set; }
        public string MKB10_Code { get; set; }
        public decimal MKB10_Id { get; set; }
    }
}
