//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagKlinPateka
    {
        public decimal DiagKlinPatekaID { get; set; }
        public decimal KlinicnaPatekaID { get; set; }
        public decimal DiagnozaID { get; set; }
    
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual KlinicnaPateka KlinicnaPateka { get; set; }
    }
}
