//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietWardPersistance
    {
        public int DietWardPersistanceID { get; set; }
        public int DietID { get; set; }
        public decimal WardID { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Diet Diet { get; set; }
        public virtual Zveno Zveno { get; set; }
    }
}
