//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DietOrder()
        {
            this.DietDelivery = new HashSet<DietDelivery>();
        }
    
        public int DietOrderID { get; set; }
        public decimal ZvenoID { get; set; }
        public int DietID { get; set; }
        public int NumberOfPatients { get; set; }
        public Nullable<int> BreakfastQuantity { get; set; }
        public Nullable<int> LunchQuantity { get; set; }
        public Nullable<int> DinnerQuantity { get; set; }
        public Nullable<int> AllDayQuantity { get; set; }
        public Nullable<int> ExtremelyDinnerQuantity { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime ExtremelyDeliveryDate { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Diet Diet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DietDelivery> DietDelivery { get; set; }
        public virtual Zveno Zveno { get; set; }
    }
}
