//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietOrderAccordance
    {
        public int DietOrderAccordanceID { get; set; }
        public int DietDeliveryID { get; set; }
        public Nullable<int> BreakfastMinorDiscrepancy { get; set; }
        public Nullable<int> BreakfastMajorDiscrepancy { get; set; }
        public Nullable<int> LunchMinorDiscrepancy { get; set; }
        public Nullable<int> LunchMajorDiscrepancy { get; set; }
        public Nullable<int> DinnerMinorDiscrepancy { get; set; }
        public Nullable<int> DinnerMajorDiscrepancy { get; set; }
        public Nullable<int> AllDayMinorDiscrepancy { get; set; }
        public Nullable<int> AllDayMajorDiscrepancy { get; set; }
        public Nullable<int> ExtremelyDinnerMinorDiscrepancy { get; set; }
        public Nullable<int> ExtremelyDinnerMajorDiscrepancy { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual DietDelivery DietDelivery { get; set; }
    }
}
