//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispProgZab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispProgZab()
        {
            this.DispProgDiag = new HashSet<DispProgDiag>();
            this.DispProgIzsl = new HashSet<DispProgIzsl>();
            this.DispProgSpec = new HashSet<DispProgSpec>();
        }
    
        public decimal DPZabID { get; set; }
        public decimal DPID { get; set; }
        public string DPZabText { get; set; }
        public string DPZabRubrika { get; set; }
        public Nullable<bool> DPZabDo18 { get; set; }
        public Nullable<bool> DPZabNad18 { get; set; }
        public string DPZabProd { get; set; }
        public string DPZabPregledi { get; set; }
        public Nullable<decimal> DPZabPBroi { get; set; }
        public string DPZabKons { get; set; }
        public string DPZabKBroi { get; set; }
        public Nullable<System.DateTime> DPZabDoData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispProgDiag> DispProgDiag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispProgIzsl> DispProgIzsl { get; set; }
        public virtual DispPrograma DispPrograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispProgSpec> DispProgSpec { get; set; }
    }
}
