//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispIzsledvane
    {
        public decimal DImzId { get; set; }
        public string DImzIme { get; set; }
        public string DImzMKB { get; set; }
        public string DImzUsluga { get; set; }
        public string KZ_DO_D6 { get; set; }
        public string OZ_DO_D4A { get; set; }
        public string PT_DO_D4В { get; set; }
        public string PZ_DO_D5A { get; set; }
        public string TZ_DO_D7A { get; set; }
    }
}
