//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispZaboliavane
    {
        public decimal DZID { get; set; }
        public string DZKod { get; set; }
        public string DZLekar { get; set; }
        public string DZIme { get; set; }
        public string DZMKB { get; set; }
        public bool DZIsDeca { get; set; }
        public bool DZIsGolemi { get; set; }
        public bool DZIsNZOK { get; set; }
        public Nullable<System.DateTime> DZDoData { get; set; }
    }
}
