//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispPrograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispPrograma()
        {
            this.DispProgZab = new HashSet<DispProgZab>();
        }
    
        public decimal DPId { get; set; }
        public decimal DPVid { get; set; }
        public string DPSad { get; set; }
        public System.DateTime DPOtData { get; set; }
        public System.DateTime DPDoData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispProgZab> DispProgZab { get; set; }
    }
}
