//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispProgDiag
    {
        public decimal DPDiagID { get; set; }
        public decimal DPZabID { get; set; }
        public decimal DPDiagnoza { get; set; }
    
        public virtual DispProgZab DispProgZab { get; set; }
    }
}
