//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorCommissionProtocol
    {
        public decimal ID { get; set; }
        public decimal AmbulatorySheetId { get; set; }
        public string ProtocolReason { get; set; }
        public string PatientProfession { get; set; }
        public string PatientWorkCity { get; set; }
        public string PatientCompany { get; set; }
        public string PatientWorkPosition { get; set; }
        public string IdentityCardNumber { get; set; }
        public Nullable<System.DateTime> PatientSickLeaveStart { get; set; }
        public Nullable<System.DateTime> PatientSickLeaveEnd { get; set; }
        public string MedicalHistory { get; set; }
        public string MeidicalState { get; set; }
        public string PatientTest { get; set; }
        public string PatientDiagnosis { get; set; }
        public string DoctorCommissionConclusion { get; set; }
        public string PatientSentTo { get; set; }
        public Nullable<decimal> ProtocolCopies { get; set; }
    
        public virtual AmbList2005 AmbList2005 { get; set; }
    }
}
