//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorsSchedule()
        {
            this.ScheduleTimeInterval = new HashSet<ScheduleTimeInterval>();
        }
    
        public int ID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal PersonalID { get; set; }
        public decimal SpecialnostPersonalID { get; set; }
        public Nullable<decimal> MedInstitutionID { get; set; }
        public bool isHospital { get; set; }
        public decimal ZvenoID { get; set; }
        public bool isActive { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleTimeInterval> ScheduleTimeInterval { get; set; }
    }
}
