//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogovorNZOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogovorNZOK()
        {
            this.DeinostNZOK = new HashSet<DeinostNZOK>();
            this.KlinicnaPateka = new HashSet<KlinicnaPateka>();
        }
    
        public decimal DogovorNzokID { get; set; }
        public string DogNzokNomer { get; set; }
        public System.DateTime DogNzokDataOt { get; set; }
        public System.DateTime DogNzokDataDo { get; set; }
        public decimal DogNZOKVid { get; set; }
        public Nullable<decimal> DogNZOKMCenter { get; set; }
        public Nullable<bool> isDogNzokAPr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeinostNZOK> DeinostNZOK { get; set; }
        public virtual MedCentar MedCentar { get; set; }
        public virtual VidDogovorNZOK VidDogovorNZOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlinicnaPateka> KlinicnaPateka { get; set; }
    }
}
