//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogovorPC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogovorPC()
        {
            this.PersonalPC = new HashSet<PersonalPC>();
        }
    
        public decimal DogovorPCId { get; set; }
        public string DogovorPCNomer { get; set; }
        public System.DateTime DogovorPCOtData { get; set; }
        public System.DateTime DogovorPCDoData { get; set; }
        public decimal DogovorPCCenter { get; set; }
        public Nullable<decimal> DogovorPCN3 { get; set; }
        public Nullable<decimal> DogovorPCN3A { get; set; }
        public Nullable<decimal> DogovorPCN4 { get; set; }
        public Nullable<decimal> DogovorPCDisp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalPC> PersonalPC { get; set; }
    }
}
