//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainToHisUsersMapping
    {
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public Nullable<int> ZvenoId { get; set; }
        public Nullable<int> PersonalId { get; set; }
    }
}
