//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EjNaznachenie
    {
        public decimal EjNaznachenieID { get; set; }
        public decimal BolID { get; set; }
        public System.DateTime EjNazData { get; set; }
        public string EjNaznachenie1 { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
    }
}
