//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalFilesVid
    {
        public decimal VFId { get; set; }
        public string VFVid { get; set; }
        public string VFIdentVid { get; set; }
        public string VFFileExtensons { get; set; }
        public string VFActiveX { get; set; }
    }
}
