//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foreigners
    {
        public string PacIme { get; set; }
        public string PacFamilia { get; set; }
        public System.DateTime PacDataNaRajdane { get; set; }
        public bool PacIsJena { get; set; }
        public decimal PacDarjava { get; set; }
    }
}
