//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FromLIS
    {
        public decimal FLId { get; set; }
        public System.DateTime FLDataR { get; set; }
        public System.DateTime FLDataM { get; set; }
        public Nullable<decimal> FLMessId { get; set; }
        public Nullable<decimal> FLPacId { get; set; }
        public string FLPacName { get; set; }
        public string FLPacEGN { get; set; }
        public Nullable<decimal> FLBolID { get; set; }
        public string FLPacIZNo { get; set; }
        public Nullable<decimal> FLOrderId { get; set; }
        public string FLIzslVid { get; set; }
        public System.DateTime FLIzslData { get; set; }
        public string FLIzslMiasto { get; set; }
        public string FLIzslNo { get; set; }
        public string FLIzslResultat { get; set; }
        public string FLIzslRefGranici { get; set; }
        public string FLIzslIzv { get; set; }
        public string FLIzslZakl { get; set; }
        public decimal FLLisResultId { get; set; }
    }
}
