//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FromPACS
    {
        public decimal FPId { get; set; }
        public System.DateTime FPDataR { get; set; }
        public System.DateTime FPDataM { get; set; }
        public decimal FPMessId { get; set; }
        public decimal FPPacId { get; set; }
        public string FPPacName { get; set; }
        public Nullable<decimal> FPBolID { get; set; }
        public string FPPacIZNo { get; set; }
        public decimal FPOrderId { get; set; }
        public string FPAccessionNo { get; set; }
        public string FPProc { get; set; }
        public System.DateTime FPIzslData { get; set; }
        public string FPImageData { get; set; }
        public string FPStatus { get; set; }
        public string FPDopDanni { get; set; }
    }
}
