//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupKlasSeb
    {
        public decimal KlasID { get; set; }
        public string GroupNo { get; set; }
        public string KlasBol { get; set; }
        public string DiagOt { get; set; }
        public string DiagDo { get; set; }
        public decimal ZaplMZ { get; set; }
    }
}
