//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMZ_0305
    {
        public decimal Id { get; set; }
        public int GroupNo { get; set; }
        public string FromDiagNO { get; set; }
        public string ToDiagNO { get; set; }
        public bool Pril5b { get; set; }
        public bool Pril6b1 { get; set; }
        public bool Pril6b2 { get; set; }
    }
}
