//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupa()
        {
            this.UslugaGrupa = new HashSet<UslugaGrupa>();
        }
    
        public decimal GrupaID { get; set; }
        public string GrupaKod { get; set; }
        public string GrupaIme { get; set; }
        public Nullable<decimal> RezPod18 { get; set; }
        public Nullable<decimal> RezNad18 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UslugaGrupa> UslugaGrupa { get; set; }
    }
}
