//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HadisToday
    {
        public int hadisId { get; set; }
        public string hadisEGN { get; set; }
        public string hadisName { get; set; }
        public System.DateTime hadisDate { get; set; }
        public string hadisDoc { get; set; }
        public string hadisEvent { get; set; }
        public string hadisType { get; set; }
        public string hadisRegistrar { get; set; }
    }
}
