//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hadis
    {
        public int Id { get; set; }
        public string PacEGN { get; set; }
        public System.DateTime PacDateOfBirth { get; set; }
        public string PacSex { get; set; }
        public string PacDocNo { get; set; }
        public string PacNames { get; set; }
        public string PacSurname { get; set; }
        public string CompEGN { get; set; }
        public string CompDocNo { get; set; }
        public string CompNames { get; set; }
        public string CompSurname { get; set; }
        public System.DateTime EventTimeStamp { get; set; }
        public string EventType { get; set; }
        public string EventInput { get; set; }
        public string EventOffline { get; set; }
        public string EventException { get; set; }
        public string EventRegistrarEGN { get; set; }
        public string EventRegistrarNames { get; set; }
        public Nullable<System.DateTime> EventSentByClient { get; set; }
        public string xmlRequest { get; set; }
        public string source { get; set; }
    }
}
