//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hadismadis
    {
        public string pacegn { get; set; }
        public string eventtype { get; set; }
        public Nullable<System.DateTime> eventtimestamp { get; set; }
        public string eventexception { get; set; }
        public string pacdocno { get; set; }
        public string eventinput { get; set; }
        public string eventoffline { get; set; }
        public string eventSource { get; set; }
    }
}
