//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hadisPresentation
    {
        public int ID { get; set; }
        public System.DateTime Час_на_регистрация { get; set; }
        public string ЕГН_на_пациент { get; set; }
        public string Име_на_пациент { get; set; }
        public string Събитие { get; set; }
        public string Тип { get; set; }
        public string regFilter { get; set; }
        public string regFilterDate { get; set; }
    }
}
