//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hemodializa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hemodializa()
        {
            this.HemodializaMedIzbran = new HashSet<HemodializaMedIzbran>();
        }
    
        public decimal HemID { get; set; }
        public decimal PacID { get; set; }
        public System.DateTime HemDataChas { get; set; }
        public Nullable<System.DateTime> HemDataChasKrai { get; set; }
        public string HemNo { get; set; }
        public Nullable<bool> HemSpeshna { get; set; }
        public decimal HemFinans { get; set; }
        public decimal HemMiasto { get; set; }
        public decimal HemLekar { get; set; }
        public Nullable<decimal> HemSestra1 { get; set; }
        public Nullable<decimal> HemSestra2 { get; set; }
        public string HemTeh { get; set; }
        public Nullable<decimal> HemVid { get; set; }
        public string HemVidDop { get; set; }
        public Nullable<decimal> HemVidMKB { get; set; }
        public string HemMKBDop { get; set; }
        public Nullable<bool> HemZOF { get; set; }
        public string HemNas { get; set; }
        public string HemNasDoc { get; set; }
        public Nullable<System.DateTime> HemNasData { get; set; }
        public Nullable<decimal> HemNasDiag { get; set; }
        public string HemNasDrugi { get; set; }
        public string HemRezultat { get; set; }
        public decimal HemDiag { get; set; }
        public string HemDiagDrugi { get; set; }
        public Nullable<decimal> HemDiagDop { get; set; }
        public string HemDrugi { get; set; }
        public Nullable<decimal> HemNas1 { get; set; }
        public Nullable<bool> HemTransport { get; set; }
        public Nullable<decimal> HemKProc { get; set; }
    
        public virtual KpLechenie KpLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HemodializaMedIzbran> HemodializaMedIzbran { get; set; }
    }
}
