//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HemodializaMedIzbran
    {
        public decimal HMIId { get; set; }
        public decimal HemID { get; set; }
        public Nullable<decimal> HemMedi { get; set; }
        public string HemMediKol { get; set; }
        public Nullable<decimal> HemMedAmount { get; set; }
    
        public virtual Hemodializa Hemodializa { get; set; }
    }
}
