//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HemodializaMed
    {
        public decimal HMId { get; set; }
        public string HMATC { get; set; }
        public string HMIme { get; set; }
        public bool HMVidim { get; set; }
        public Nullable<decimal> HMSort { get; set; }
        public string HMKodNZOK { get; set; }
        public decimal HMStoinost { get; set; }
        public string HMMiarka { get; set; }
    }
}
