//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hipExam
    {
        public int pacientId { get; set; }
        public int amb_listn { get; set; }
        public string main_diag_mkb { get; set; }
        public System.DateTime start_Date { get; set; }
        public string ANAMN { get; set; }
        public string SYST { get; set; }
        public string IZSL { get; set; }
        public string TERAPY { get; set; }
        public string docfname { get; set; }
        public string doclname { get; set; }
        public int id { get; set; }
    }
}
