//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpGroupMap_2015
    {
        public int ImpGroupMapID { get; set; }
        public string ImpGroup { get; set; }
        public string ImpType { get; set; }
        public string ImpThCode { get; set; }
        public string ImpGroupRes { get; set; }
        public string ImpTypeRes { get; set; }
        public string ImpThRes { get; set; }
    }
}
