//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpKPDiag_2015
    {
        public int id { get; set; }
        public string kpkod { get; set; }
        public string diagkod { get; set; }
        public string MEKodTip { get; set; }
        public string MEKodTH { get; set; }
    }
}
