//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImplantantNZOKDealer
    {
        public decimal DMEId { get; set; }
        public string DMEKod { get; set; }
        public string DMEDealer { get; set; }
        public Nullable<decimal> DMEStoinost { get; set; }
        public Nullable<decimal> DMEStoinostSistema { get; set; }
        public bool DMEInvisible { get; set; }
    }
}
