//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implantant
    {
        public decimal ImplantantID { get; set; }
        public decimal KPIId { get; set; }
        public System.DateTime ImpData { get; set; }
        public Nullable<decimal> ImpVid { get; set; }
        public Nullable<decimal> ImpProc { get; set; }
        public string ImpFabNo { get; set; }
        public Nullable<decimal> ImpFirma { get; set; }
        public string ImpFakNo { get; set; }
        public Nullable<System.DateTime> ImpFakData { get; set; }
        public Nullable<decimal> ImpDopZap { get; set; }
        public Nullable<decimal> ImpStoinost { get; set; }
        public Nullable<decimal> OperaciaID { get; set; }
        public Nullable<decimal> ProID { get; set; }
        public Nullable<decimal> DIIID { get; set; }
        public Nullable<decimal> IPID { get; set; }
        public Nullable<decimal> BolId { get; set; }
        public Nullable<bool> ImpZapNZOK { get; set; }
        public string ImpTargovsko { get; set; }
        public string ImpKatNomer { get; set; }
        public string ImpProizvoditel { get; set; }
        public string ImpGrupa { get; set; }
        public string ImpDealer { get; set; }
        public Nullable<decimal> ImpCenaNZOK { get; set; }
        public string ImpCodeNZOK { get; set; }
        public Nullable<bool> ImpSistema { get; set; }
        public string ImpSklNo { get; set; }
        public Nullable<decimal> EFIID { get; set; }
    
        public virtual IzsEFI IzsEFI { get; set; }
        public virtual IzsDI IzsDI { get; set; }
        public virtual IzsIP IzsIP { get; set; }
        public virtual KlinPatImpl KlinPatImpl { get; set; }
        public virtual Operacia Operacia { get; set; }
        public virtual Proceduri Proceduri { get; set; }
    }
}
