//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImplantantDop
    {
        public decimal BLDopID { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> BlDopData { get; set; }
        public Nullable<decimal> BlDopKPID { get; set; }
        public Nullable<decimal> BlDopImpID { get; set; }
        public Nullable<decimal> BlDopDii { get; set; }
        public Nullable<decimal> BlDopOP { get; set; }
        public Nullable<decimal> BlDopIP { get; set; }
        public Nullable<decimal> BlDopPro { get; set; }
        public Nullable<decimal> BlDopDiag { get; set; }
    }
}
