//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntLechenie
    {
        public decimal ILId { get; set; }
        public decimal BolID { get; set; }
        public Nullable<decimal> PrevejdaneID { get; set; }
        public System.DateTime ILDataChas { get; set; }
        public string ILHemod { get; set; }
        public string ILRPNar { get; set; }
        public string ILDihProb { get; set; }
        public string ILInfek { get; set; }
        public Nullable<decimal> ILAparVent { get; set; }
        public string ILPrep { get; set; }
        public Nullable<bool> ILO1 { get; set; }
        public Nullable<bool> ILO2 { get; set; }
        public Nullable<bool> ILO3 { get; set; }
        public Nullable<bool> ILO4 { get; set; }
        public Nullable<bool> IRO1 { get; set; }
        public Nullable<bool> IRO2 { get; set; }
        public Nullable<bool> IRO3 { get; set; }
        public Nullable<bool> IRO4 { get; set; }
        public Nullable<bool> IRO5 { get; set; }
        public Nullable<bool> IDO1 { get; set; }
        public Nullable<bool> IDO2 { get; set; }
        public Nullable<bool> IDO3 { get; set; }
        public Nullable<bool> IDO4 { get; set; }
        public Nullable<bool> IDO5 { get; set; }
        public Nullable<bool> IDO6 { get; set; }
        public string ILOzenka { get; set; }
        public Nullable<decimal> ILDiag { get; set; }
        public Nullable<decimal> ILPrModel { get; set; }
        public Nullable<decimal> ILDiagModel { get; set; }
        public string ILProtokol { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Prevejdane Prevejdane { get; set; }
    }
}
