//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzdNaprNZOK
    {
        public decimal NaprID { get; set; }
        public Nullable<decimal> NaprFniID { get; set; }
        public Nullable<decimal> NaprProID { get; set; }
        public Nullable<decimal> NaprPregledID { get; set; }
        public string NaprVid { get; set; }
        public Nullable<System.DateTime> NaprData { get; set; }
        public string NaprNo { get; set; }
        public Nullable<decimal> NaprTip { get; set; }
        public Nullable<decimal> Napr3Spec { get; set; }
        public Nullable<decimal> Napr4Vid1 { get; set; }
        public Nullable<decimal> Napr4Vid2 { get; set; }
        public Nullable<decimal> Napr4Vid3 { get; set; }
        public Nullable<decimal> Napr4Vid4 { get; set; }
        public Nullable<decimal> Napr4Vid5 { get; set; }
        public Nullable<decimal> Napr4Vid6 { get; set; }
        public Nullable<bool> NaprBol { get; set; }
        public Nullable<decimal> NaprVSD { get; set; }
        public Nullable<bool> NaprSam { get; set; }
        public Nullable<decimal> NaprME1 { get; set; }
        public Nullable<decimal> NaprME2 { get; set; }
        public Nullable<decimal> NaprME3 { get; set; }
        public Nullable<decimal> NaprME4 { get; set; }
        public Nullable<decimal> NaprME5 { get; set; }
        public Nullable<decimal> Napr7Izd { get; set; }
        public Nullable<decimal> Napr7Lekar { get; set; }
        public Nullable<bool> Napr7Speshen { get; set; }
        public string Napr7KP { get; set; }
        public Nullable<decimal> Napr7Diag1 { get; set; }
        public Nullable<decimal> Napr7DiagD1 { get; set; }
        public Nullable<decimal> Napr7Diag2 { get; set; }
        public Nullable<decimal> Napr7DiagD2 { get; set; }
    
        public virtual IzsFNI IzsFNI { get; set; }
        public virtual Pregled Pregled { get; set; }
        public virtual Proceduri Proceduri { get; set; }
    }
}
