//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzoliranMikroorganizamData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzoliranMikroorganizamData()
        {
            this.MikrobiologichnoIzsledvane = new HashSet<MikrobiologichnoIzsledvane>();
        }
    
        public int IzoliranMikroorganizamDataId { get; set; }
        public Nullable<decimal> KolichestvenaOcenkaNomId { get; set; }
        public string MikrobnoChislo { get; set; }
    
        public virtual Nomenklatura Nomenklatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MikrobiologichnoIzsledvane> MikrobiologichnoIzsledvane { get; set; }
    }
}
