//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsDI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzsDI()
        {
            this.Anestezia = new HashSet<Anestezia>();
            this.Antro_pok = new HashSet<Antro_pok>();
            this.Implantant = new HashSet<Implantant>();
            this.IzsDI_Res = new HashSet<IzsDI_Res>();
        }
    
        public decimal DiiID { get; set; }
        public System.DateTime DiiDataChas { get; set; }
        public Nullable<System.DateTime> DiiProd { get; set; }
        public decimal DiiKamOtch { get; set; }
        public string DiiNo { get; set; }
        public decimal DiiFinans { get; set; }
        public Nullable<bool> DiiDopZOF { get; set; }
        public Nullable<decimal> DiiVid { get; set; }
        public string DiiVidDop { get; set; }
        public Nullable<decimal> DiiVidMKB { get; set; }
        public string DiiMKBDop { get; set; }
        public decimal DiiMiasto { get; set; }
        public Nullable<decimal> DiiLekar1 { get; set; }
        public Nullable<decimal> DiiLekar2 { get; set; }
        public string DiiEkip { get; set; }
        public bool DiiIsSpeshen { get; set; }
        public Nullable<decimal> DiiNasZveno { get; set; }
        public Nullable<decimal> DiiNasVun { get; set; }
        public string DiiNasDoc { get; set; }
        public Nullable<System.DateTime> DiiNasData { get; set; }
        public Nullable<decimal> DiiNasDiag { get; set; }
        public string DiiNasDrugi { get; set; }
        public string DiiPrem { get; set; }
        public Nullable<decimal> DiiSadDost { get; set; }
        public string DiiKoron { get; set; }
        public string DiiAngio { get; set; }
        public string DiiSelAngio { get; set; }
        public string DiiHemo { get; set; }
        public Nullable<System.DateTime> DiiRentgenTime { get; set; }
        public Nullable<decimal> DiiKontVid { get; set; }
        public string DiiKontKol { get; set; }
        public string DiiMedik { get; set; }
        public decimal DiiDiag { get; set; }
        public string DiiDopDiag { get; set; }
        public string DiiDrugi { get; set; }
        public string DiiUsloj { get; set; }
        public string DiiZak { get; set; }
        public string DiiCDNo { get; set; }
        public string DiiProtSave { get; set; }
        public decimal PacID { get; set; }
        public Nullable<decimal> BolID { get; set; }
        public Nullable<decimal> DiiLekar3 { get; set; }
        public Nullable<decimal> DiiIzhod { get; set; }
        public Nullable<decimal> DiiSyntax { get; set; }
        public Nullable<decimal> DiiRoDoza { get; set; }
        public Nullable<decimal> DiiMERoDoza { get; set; }
        public Nullable<int> DiiVidMKB2 { get; set; }
        public Nullable<int> DiiVidMKB3 { get; set; }
        public string DiiMKBDop2 { get; set; }
        public string DiiMKBDop3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anestezia> Anestezia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antro_pok> Antro_pok { get; set; }
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Diagnoza Diagnoza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Implantant> Implantant { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Nomenklatura Nomenklatura2 { get; set; }
        public virtual Nomenklatura Nomenklatura3 { get; set; }
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzsDI_Res> IzsDI_Res { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Zveno Zveno1 { get; set; }
    }
}
