//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsEFI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzsEFI()
        {
            this.Anestezia = new HashSet<Anestezia>();
            this.Implantant = new HashSet<Implantant>();
        }
    
        public decimal EfiId { get; set; }
        public System.DateTime EfiDataChas { get; set; }
        public Nullable<System.DateTime> EfiProd { get; set; }
        public decimal EfiKamOtch { get; set; }
        public string EfiNo { get; set; }
        public decimal EfiFinans { get; set; }
        public Nullable<bool> EfiDopZOF { get; set; }
        public Nullable<decimal> EfiVid { get; set; }
        public string EfiVidDop { get; set; }
        public Nullable<decimal> EfiMKB { get; set; }
        public string EfiMkbDop { get; set; }
        public decimal EfiMiasto { get; set; }
        public decimal EfiLekar1 { get; set; }
        public Nullable<decimal> EfiLekar2 { get; set; }
        public string EfiEkip { get; set; }
        public bool EfiSpeshno { get; set; }
        public Nullable<decimal> EfiNasZveno { get; set; }
        public Nullable<decimal> EfiNasVun { get; set; }
        public string EfiNasDoc { get; set; }
        public Nullable<System.DateTime> EfiNasData { get; set; }
        public Nullable<decimal> EfiNasDiag { get; set; }
        public string EfiNasDrugi { get; set; }
        public string EfiPrem { get; set; }
        public Nullable<decimal> EfiKontVid { get; set; }
        public string EfiKontKol { get; set; }
        public Nullable<System.DateTime> EfiRentgenTime { get; set; }
        public string EfiMedik { get; set; }
        public string EfiBazRitam { get; set; }
        public string EfiBrKat { get; set; }
        public string EfiDrRez { get; set; }
        public string EfiRFAMiasto { get; set; }
        public string EfiRFAProd { get; set; }
        public string EfiRFATemp { get; set; }
        public string EfiRFAMo { get; set; }
        public string EfiRFABr { get; set; }
        public string EfiRFADrugi { get; set; }
        public decimal EfiDiag { get; set; }
        public string EfiDopDiag { get; set; }
        public string EfiDrugi { get; set; }
        public string EfiUsloj { get; set; }
        public string EfiZak { get; set; }
        public string EfiProtSave { get; set; }
        public Nullable<decimal> BolID { get; set; }
        public decimal PacID { get; set; }
        public Nullable<decimal> EfiMKB2 { get; set; }
        public Nullable<decimal> EfiMKB3 { get; set; }
        public string EfiMKBDop2 { get; set; }
        public string EfiMKBDop3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anestezia> Anestezia { get; set; }
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Diagnoza Diagnoza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Implantant> Implantant { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Nomenklatura Nomenklatura2 { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Zveno Zveno1 { get; set; }
    }
}
