//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsIP_Res
    {
        public decimal IPRId { get; set; }
        public decimal IpID { get; set; }
        public Nullable<decimal> IPRHb { get; set; }
        public Nullable<decimal> IPRKk { get; set; }
        public Nullable<decimal> C11 { get; set; }
        public Nullable<decimal> C12 { get; set; }
        public Nullable<decimal> C13 { get; set; }
        public Nullable<decimal> C21 { get; set; }
        public Nullable<decimal> C22 { get; set; }
        public Nullable<decimal> C23 { get; set; }
        public Nullable<decimal> C31 { get; set; }
        public Nullable<decimal> C32 { get; set; }
        public Nullable<decimal> C33 { get; set; }
        public Nullable<decimal> C41 { get; set; }
        public Nullable<decimal> C42 { get; set; }
        public Nullable<decimal> C43 { get; set; }
        public Nullable<decimal> C51 { get; set; }
        public Nullable<decimal> C52 { get; set; }
        public Nullable<decimal> C53 { get; set; }
        public Nullable<decimal> C61 { get; set; }
        public Nullable<decimal> C62 { get; set; }
        public Nullable<decimal> C63 { get; set; }
        public Nullable<decimal> C71 { get; set; }
        public Nullable<decimal> C72 { get; set; }
        public Nullable<decimal> C73 { get; set; }
        public Nullable<decimal> C81 { get; set; }
        public Nullable<decimal> C82 { get; set; }
        public Nullable<decimal> C83 { get; set; }
        public Nullable<decimal> C91 { get; set; }
        public Nullable<decimal> C92 { get; set; }
        public Nullable<decimal> C93 { get; set; }
        public Nullable<decimal> C101 { get; set; }
        public Nullable<decimal> C102 { get; set; }
        public Nullable<decimal> C103 { get; set; }
        public Nullable<decimal> C111 { get; set; }
        public Nullable<decimal> C112 { get; set; }
        public Nullable<decimal> C113 { get; set; }
        public Nullable<decimal> D11 { get; set; }
        public Nullable<decimal> D12 { get; set; }
        public Nullable<decimal> D13 { get; set; }
        public Nullable<decimal> D21 { get; set; }
        public Nullable<decimal> D22 { get; set; }
        public Nullable<decimal> D23 { get; set; }
        public Nullable<decimal> D31 { get; set; }
        public Nullable<decimal> D32 { get; set; }
        public Nullable<decimal> D33 { get; set; }
        public Nullable<decimal> D41 { get; set; }
        public Nullable<decimal> D42 { get; set; }
        public Nullable<decimal> D43 { get; set; }
        public Nullable<decimal> D51 { get; set; }
        public Nullable<decimal> D52 { get; set; }
        public Nullable<decimal> D53 { get; set; }
        public Nullable<decimal> D61 { get; set; }
        public Nullable<decimal> D62 { get; set; }
        public Nullable<decimal> D63 { get; set; }
        public Nullable<decimal> D71 { get; set; }
        public Nullable<decimal> D72 { get; set; }
        public Nullable<decimal> D73 { get; set; }
        public Nullable<decimal> D81 { get; set; }
        public Nullable<decimal> D82 { get; set; }
        public Nullable<decimal> D83 { get; set; }
        public Nullable<decimal> D91 { get; set; }
        public Nullable<decimal> D92 { get; set; }
        public Nullable<decimal> D93 { get; set; }
        public Nullable<decimal> D101 { get; set; }
        public Nullable<decimal> D102 { get; set; }
        public Nullable<decimal> D103 { get; set; }
        public Nullable<decimal> D111 { get; set; }
        public Nullable<decimal> D112 { get; set; }
        public Nullable<decimal> D113 { get; set; }
    
        public virtual IzsIP IzsIP { get; set; }
    }
}
