//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsLabPaket
    {
        public decimal IzsLabPaketID { get; set; }
        public Nullable<decimal> IzsLabPaketSelfID { get; set; }
        public string IzsLabPaketIme { get; set; }
        public Nullable<decimal> IzsLabPaketUslugaID { get; set; }
        public bool IzsLabPaketIsNZOK { get; set; }
    }
}
