//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsLABINRDanni
    {
        public decimal INRDId { get; set; }
        public decimal LabID { get; set; }
        public decimal INRDInr { get; set; }
        public decimal INRDDosa { get; set; }
        public decimal INRDMedikament { get; set; }
        public string INRDLechenie { get; set; }
        public Nullable<decimal> INRDSabitie { get; set; }
        public Nullable<decimal> INRDProcedura { get; set; }
        public Nullable<System.DateTime> INRDDataKontrol { get; set; }
        public string INRDZabelejki { get; set; }
        public string INRDd1 { get; set; }
        public string INRDd2 { get; set; }
        public string INRDd3 { get; set; }
        public string INRDd4 { get; set; }
        public string INRDd5 { get; set; }
        public string INRDd6 { get; set; }
        public string INRDd7 { get; set; }
        public Nullable<decimal> INRDRisk { get; set; }
        public Nullable<decimal> INRDDiapasonOt { get; set; }
        public Nullable<decimal> INRDDiapasonDo { get; set; }
    
        public virtual IzsLAB IzsLAB { get; set; }
    }
}
