//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsMDI
    {
        public decimal MDIID { get; set; }
        public System.DateTime MDIDataChas { get; set; }
        public Nullable<System.DateTime> MDIDataChasKrai { get; set; }
        public Nullable<decimal> MDIKamOtch { get; set; }
        public Nullable<decimal> MDIFinans { get; set; }
        public string MDIVid { get; set; }
        public Nullable<decimal> MDIVidMKB { get; set; }
        public decimal MDIMiasto { get; set; }
        public Nullable<decimal> MDILekar { get; set; }
        public bool MDISpeshno { get; set; }
        public string MDIRezultat { get; set; }
        public decimal MDIDiag { get; set; }
        public string MDIDopDiag { get; set; }
        public Nullable<decimal> MDIDiagDop { get; set; }
        public string MDIDrugi { get; set; }
        public string MDIZak { get; set; }
        public bool MDDispanser { get; set; }
        public bool MDIIsVSD { get; set; }
        public int MDIVidBroi { get; set; }
        public decimal PacID { get; set; }
        public decimal KpLechenieID { get; set; }
    }
}
