//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsROD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzsROD()
        {
            this.OrderEntry = new HashSet<OrderEntry>();
        }
    
        public decimal RodID { get; set; }
        public System.DateTime RodDataChas { get; set; }
        public decimal RodKamOtch { get; set; }
        public string RodNo { get; set; }
        public decimal RodFinans { get; set; }
        public Nullable<decimal> RodVid { get; set; }
        public string RodVidDop { get; set; }
        public Nullable<decimal> RodVidMKB { get; set; }
        public string RodMKBDop { get; set; }
        public decimal RodMiasto { get; set; }
        public Nullable<decimal> RodLekar { get; set; }
        public bool RodSpeshno { get; set; }
        public Nullable<decimal> RodZapl { get; set; }
        public Nullable<decimal> RodNasZveno { get; set; }
        public Nullable<decimal> RodNasVun { get; set; }
        public string RodNasDoc { get; set; }
        public Nullable<System.DateTime> RodNasData { get; set; }
        public Nullable<decimal> RodNasDiag { get; set; }
        public string RodNasDrugi { get; set; }
        public string RodRezultat { get; set; }
        public decimal RodDiag { get; set; }
        public string RodDopDiag { get; set; }
        public Nullable<decimal> RodDiagDop { get; set; }
        public string RodDrugi { get; set; }
        public string RodZak { get; set; }
        public bool RodProfilakt { get; set; }
        public bool RodDispanser { get; set; }
        public string RodProtSave { get; set; }
        public decimal PacID { get; set; }
        public Nullable<decimal> BolID { get; set; }
        public Nullable<decimal> NasID { get; set; }
        public string RodProtRes { get; set; }
        public Nullable<decimal> KpLechenieID { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Zveno Zveno1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEntry> OrderEntry { get; set; }
    }
}
