//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsVSI
    {
        public decimal VsiID { get; set; }
        public System.DateTime VsiDataChas { get; set; }
        public decimal VsiKamOtch { get; set; }
        public string VsiNo { get; set; }
        public decimal VsiFinans { get; set; }
        public Nullable<decimal> VsiVid { get; set; }
        public string VsiVidDop { get; set; }
        public Nullable<decimal> VsiVidMKB { get; set; }
        public string VsiMKBDop { get; set; }
        public decimal VsiMiasto { get; set; }
        public decimal VsiLekar { get; set; }
        public bool VsiSpeshno { get; set; }
        public Nullable<decimal> VsiNasZveno { get; set; }
        public Nullable<decimal> VsiNasVun { get; set; }
        public string VsiNasDoc { get; set; }
        public Nullable<System.DateTime> VsiNasData { get; set; }
        public Nullable<decimal> VsiNasDiag { get; set; }
        public string VsiNasDrugi { get; set; }
        public string VsiRezultat { get; set; }
        public decimal VsiDiag { get; set; }
        public string VsiDopDiag { get; set; }
        public string VsiDrugi { get; set; }
        public string VsiZak { get; set; }
        public string VsiVideoProt { get; set; }
        public string VsiKaseta { get; set; }
        public bool VsiProfilakt { get; set; }
        public bool VsiDispanser { get; set; }
        public string VsiNoMDD { get; set; }
        public Nullable<System.DateTime> VsiOtData { get; set; }
        public string VsiAmbList { get; set; }
        public string VsiAmbNo { get; set; }
        public string VsiNoZZ { get; set; }
        public string VsiEGN_IzprLekar { get; set; }
        public string VsiUIN_IzprLekar { get; set; }
        public string VsiKodSpec { get; set; }
        public Nullable<int> VsiNomerPored { get; set; }
        public string VsiKodMKB { get; set; }
        public string VsiKodMKB1 { get; set; }
        public bool VsiExec1 { get; set; }
        public string VsiKodMKB2 { get; set; }
        public bool VsiExec2 { get; set; }
        public string VsiKodMKB3 { get; set; }
        public bool VsiExec3 { get; set; }
        public string VsiKodMKB4 { get; set; }
        public bool VsiExec4 { get; set; }
        public string VsiKodMKB5 { get; set; }
        public bool VsiExec5 { get; set; }
        public bool VsiIzprLKK { get; set; }
        public Nullable<decimal> VsiNasDiagMDD { get; set; }
        public bool VsiNaprOthv { get; set; }
        public bool VsiZaRZOK { get; set; }
        public string VsiProtSave { get; set; }
        public decimal PacID { get; set; }
        public Nullable<decimal> BolID { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Diagnoza Diagnoza1 { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Zveno Zveno1 { get; set; }
    }
}
