//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzsVPI
    {
        public decimal VpiID { get; set; }
        public System.DateTime VpiDataChas { get; set; }
        public decimal VpiKamOtch { get; set; }
        public string VpiNo { get; set; }
        public decimal VpiFinans { get; set; }
        public decimal VpiVidMKB { get; set; }
        public string VpiMKBDop { get; set; }
        public bool VpiSpeshno { get; set; }
        public decimal VpiDiag { get; set; }
        public string VpiDopDiag { get; set; }
        public Nullable<decimal> VpiDiagDop { get; set; }
        public string VpiDrugi { get; set; }
        public string VpiZak { get; set; }
        public decimal PacID { get; set; }
        public decimal BolID { get; set; }
    }
}
