//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzvunNKBKons
    {
        public decimal IzvID { get; set; }
        public System.DateTime IzvDataChas { get; set; }
        public Nullable<decimal> IzvZdrZav { get; set; }
        public decimal IzvLekarID { get; set; }
        public bool IzvIsSpeshna { get; set; }
        public string IzvVreme { get; set; }
        public string IzvOpisanie { get; set; }
        public string IzvZakluchenie { get; set; }
    
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
