//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kalkulacia
    {
        public decimal KalkulaciaID { get; set; }
        public Nullable<decimal> PacientID { get; set; }
        public Nullable<decimal> MedCentar { get; set; }
        public Nullable<int> KalkulaciaType { get; set; }
        public Nullable<int> KalkulaciaSubType { get; set; }
        public string KalkulaciaIme { get; set; }
        public Nullable<decimal> KalkulaciaCena { get; set; }
        public Nullable<decimal> KalkulaciaBroi { get; set; }
        public string KalkulaciaDates { get; set; }
        public Nullable<System.DateTime> KalkulaciaDate { get; set; }
        public string KalkulaciaPrestoi { get; set; }
    }
}
