//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlinPatImplCena
    {
        public decimal KPICId { get; set; }
        public decimal KPIId { get; set; }
        public Nullable<System.DateTime> KPICData { get; set; }
        public Nullable<decimal> KPICena { get; set; }
        public bool KPICIsParv { get; set; }
    
        public virtual KlinPatImpl KlinPatImpl { get; set; }
    }
}
