//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlinPatImpl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KlinPatImpl()
        {
            this.Implantant = new HashSet<Implantant>();
            this.KlinPatImplCena = new HashSet<KlinPatImplCena>();
        }
    
        public decimal KPIId { get; set; }
        public decimal KlinicnaPatekaID { get; set; }
        public string KPIKod { get; set; }
        public decimal KPIVid { get; set; }
        public Nullable<bool> KPIDDS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Implantant> Implantant { get; set; }
        public virtual KlinicnaPateka KlinicnaPateka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlinPatImplCena> KlinPatImplCena { get; set; }
    }
}
