//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlinicnaPateka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KlinicnaPateka()
        {
            this.BolnichnoLechenie = new HashSet<BolnichnoLechenie>();
            this.BolnichnoLechenie1 = new HashSet<BolnichnoLechenie>();
            this.DiagKlinPateka = new HashSet<DiagKlinPateka>();
            this.KlinPatekaCena = new HashSet<KlinPatekaCena>();
            this.KlinPatImpl = new HashSet<KlinPatImpl>();
        }
    
        public decimal KlinicnaPatekaID { get; set; }
        public decimal DogovorNzokID { get; set; }
        public string KlinPatKod { get; set; }
        public string KlinPatIme { get; set; }
        public decimal KlinPatStoinost { get; set; }
        public Nullable<decimal> KlinPatPerNekorRehosp { get; set; }
        public string KlinPatPreporPrestoi { get; set; }
        public Nullable<bool> KlinPatIsLegloden { get; set; }
        public string KlinPatMinPrestoi { get; set; }
        public bool KlinPatIsAktivna { get; set; }
        public decimal KlinPatImplantanti { get; set; }
        public Nullable<decimal> KlinPatDPBroi { get; set; }
        public Nullable<decimal> KlinPatTPBroi { get; set; }
        public Nullable<decimal> KlinPatOPBroi { get; set; }
        public bool KlinPatSpec { get; set; }
        public string KlinPatDPZad { get; set; }
        public string KlinPatTPZad { get; set; }
        public string KlinPatOPZad { get; set; }
        public int KlinPatMinPrestoiCheck { get; set; }
        public bool HasSecondDiag { get; set; }
        public bool isKlinPatAPr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagKlinPateka> DiagKlinPateka { get; set; }
        public virtual DogovorNZOK DogovorNZOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlinPatekaCena> KlinPatekaCena { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlinPatImpl> KlinPatImpl { get; set; }
    }
}
