//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komitet
    {
        public decimal KomitetID { get; set; }
        public decimal PacID { get; set; }
        public decimal KomReshenieNo { get; set; }
        public System.DateTime KomDataChas { get; set; }
        public decimal KomVid { get; set; }
        public bool KomIsParvichno { get; set; }
        public string KomNachalo { get; set; }
        public string KomIziava { get; set; }
        public string KomParvReshenie { get; set; }
        public string KomPovod { get; set; }
        public string KomPridrZab { get; set; }
        public string KomSimptomi { get; set; }
        public string KomNahodka { get; set; }
        public string KomBiopsii { get; set; }
        public string KomMielograma { get; set; }
        public string KomFlow { get; set; }
        public string KomLab { get; set; }
        public string KomCito { get; set; }
        public string KomTrepan { get; set; }
        public string KomCitogen { get; set; }
        public string KomMolAnaliz { get; set; }
        public string KomObrazna { get; set; }
        public string KomDrugiObrazni { get; set; }
        public string KomScintio { get; set; }
        public string KomStadii { get; set; }
        public string KomLechenie { get; set; }
        public string KomProgFactor { get; set; }
        public string KomToks { get; set; }
        public string KomRisk { get; set; }
        public string KomReshenie { get; set; }
        public decimal KomPredstavil { get; set; }
        public string KomExpGrupa { get; set; }
        public decimal KomDiag { get; set; }
        public Nullable<decimal> KomDiagDop { get; set; }
        public string KomDiagDrugi { get; set; }
        public string KomDrugi { get; set; }
        public string KomProtSave { get; set; }
        public string KomHemNeo { get; set; }
    
        public virtual Pacient Pacient { get; set; }
    }
}
