//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konsultacia
    {
        public decimal KonID { get; set; }
        public decimal KonPacID { get; set; }
        public bool KonIsVun { get; set; }
        public System.DateTime KonDataChas { get; set; }
        public decimal KonMiasto { get; set; }
        public decimal KonFinansirane { get; set; }
        public Nullable<decimal> KonLekarID { get; set; }
        public string KonVunIme { get; set; }
        public Nullable<decimal> KonVunSpe { get; set; }
        public Nullable<decimal> KonVunZdrZav { get; set; }
        public bool KonIsSpeshna { get; set; }
        public string KonVreme { get; set; }
        public bool KonIsOperativna { get; set; }
        public string KonOpisanie { get; set; }
        public Nullable<decimal> KonDiagnoza { get; set; }
        public string KonDopDanni { get; set; }
        public string KonRezultat { get; set; }
        public string KonDopNaz { get; set; }
        public Nullable<decimal> KonUslugaID { get; set; }
        public string Protocol { get; set; }
        public bool KonVunIsRep { get; set; }
        public Nullable<decimal> BolId { get; set; }
        public Nullable<decimal> KonSpecializant { get; set; }
        public Nullable<decimal> KonStoinost { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Nomenklatura Nomenklatura2 { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Zveno Zveno { get; set; }
    }
}
