//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeglovaBaza
    {
        public decimal LeglovaBazaID { get; set; }
        public decimal ZvenoID { get; set; }
        public System.DateTime LegBazaDataOt { get; set; }
        public System.DateTime LegBazaDataDo { get; set; }
        public decimal LegBazaPlanRazkr { get; set; }
        public Nullable<decimal> LegBazaRealRazkrM { get; set; }
        public Nullable<decimal> LegBazaRealRazkrF { get; set; }
        public Nullable<decimal> LegBazaRealRazkrVip { get; set; }
        public Nullable<decimal> LegBazaPlanNzok { get; set; }
    
        public virtual Zveno Zveno { get; set; }
    }
}
