//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitiNZOK
    {
        public decimal LimID { get; set; }
        public Nullable<decimal> LimBolID { get; set; }
        public Nullable<decimal> LimMedCentarID { get; set; }
        public decimal LimVidNapr { get; set; }
        public System.DateTime LimOtData { get; set; }
        public System.DateTime LimDoData { get; set; }
        public Nullable<decimal> LimBroi { get; set; }
        public Nullable<decimal> LimCena { get; set; }
    
        public virtual Bolnica Bolnica { get; set; }
        public virtual MedCentar MedCentar { get; set; }
    }
}
