//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkkCommissions
    {
        public decimal id { get; set; }
        public string LKKName { get; set; }
        public int LKKKind { get; set; }
        public string LKKuin0 { get; set; }
        public string LKKuin1 { get; set; }
        public string LKKuin2 { get; set; }
        public string LKKuin3 { get; set; }
        public string LKKuin4 { get; set; }
        public string LKKuin5 { get; set; }
        public string LKKuin6 { get; set; }
        public string LKKuin7 { get; set; }
        public string LKKuin8 { get; set; }
        public string LKKuin9 { get; set; }
        public string LKKuin10 { get; set; }
        public string LKKuin11 { get; set; }
        public string LKKDoctorName0 { get; set; }
        public string LKKDoctorName1 { get; set; }
        public string LKKDoctorName2 { get; set; }
        public string LKKDoctorName3 { get; set; }
        public string LKKDoctorName4 { get; set; }
        public string LKKDoctorName5 { get; set; }
        public string LKKDoctorName6 { get; set; }
        public string LKKDoctorName7 { get; set; }
        public string LKKDoctorName8 { get; set; }
        public string LKKDoctorName9 { get; set; }
        public string LKKDoctorName10 { get; set; }
        public string LKKDoctorName11 { get; set; }
        public string LKKSpec0 { get; set; }
        public string LKKSpec1 { get; set; }
        public string LKKSpec2 { get; set; }
        public string LKKSpec3 { get; set; }
        public string LKKSpec4 { get; set; }
        public string LKKSpec5 { get; set; }
        public string LKKSpec6 { get; set; }
        public string LKKSpec7 { get; set; }
        public string LKKSpec8 { get; set; }
        public string LKKSpec9 { get; set; }
        public string LKKSpec10 { get; set; }
        public string LKKSpec11 { get; set; }
        public string CommissionSpeciality { get; set; }
    }
}
