//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class madis
    {
        public int Id { get; set; }
        public string SenderEntityCode { get; set; }
        public string SenderEIK { get; set; }
        public string SenderIDN { get; set; }
        public string SenderName { get; set; }
        public string PersonIDNType { get; set; }
        public string PersonIDN { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonSecondName { get; set; }
        public string PersonThirdName { get; set; }
        public string PersonDOB { get; set; }
        public string PersonExceptionID { get; set; }
        public string PersonExceptionCode { get; set; }
        public string PersonExceptionName { get; set; }
        public string AttendantIDNType { get; set; }
        public string AttendantIDN { get; set; }
        public string AttendantFirstName { get; set; }
        public string AttendantSecondName { get; set; }
        public string AttendantThirdName { get; set; }
        public string AttendantExceptionID { get; set; }
        public string AttendantExceptionCode { get; set; }
        public string AttendantExceptionName { get; set; }
        public string EventTypeID { get; set; }
        public string EventTypeCode { get; set; }
        public string EventTypeName { get; set; }
        public string EventEventTime { get; set; }
        public string EventCaptureType { get; set; }
        public string EventCaseNum { get; set; }
        public string xmlRequest { get; set; }
        public System.DateTime requestTimeStamp { get; set; }
    }
}
