//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MartvoRodeni
    {
        public decimal MRID { get; set; }
        public decimal BolID { get; set; }
        public decimal PacID { get; set; }
        public Nullable<decimal> MRVid1 { get; set; }
        public Nullable<decimal> MRVid2 { get; set; }
        public Nullable<decimal> MRVid3 { get; set; }
        public Nullable<decimal> MRVid4 { get; set; }
        public Nullable<decimal> MRVid5 { get; set; }
        public Nullable<decimal> MRVid6 { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
