//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedDiagDeinost
    {
        public decimal MDDId { get; set; }
        public decimal MDDNo { get; set; }
        public string MDDIme { get; set; }
        public string MDDKod { get; set; }
        public decimal MDDUsId { get; set; }
    }
}
