//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedTerapia
    {
        public decimal MedTerapiaID { get; set; }
        public decimal BolID { get; set; }
        public System.DateTime MedDataChas { get; set; }
        public Nullable<decimal> MedVlagane { get; set; }
        public string Medikament { get; set; }
        public string MedDrugi { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
    }
}
