//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MikroskopskiPreparatData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MikroskopskiPreparatData()
        {
            this.MikrobiologichnoIzsledvane = new HashSet<MikrobiologichnoIzsledvane>();
        }
    
        public int MikroskopskiPreparatDataId { get; set; }
        public Nullable<decimal> BakteuriaNomId { get; set; }
        public string BakteuriaValue { get; set; }
        public string MikroskopskiPreparatDop { get; set; }
        public bool VeroiatenZamursitel { get; set; }
        public bool NormalnaMikroflora { get; set; }
        public bool SterilniPosevki { get; set; }
        public string Preporuki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MikrobiologichnoIzsledvane> MikrobiologichnoIzsledvane { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
    }
}
