//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOIProverkaOSV
    {
        public decimal NOIOSVId { get; set; }
        public decimal PacientID { get; set; }
        public System.DateTime NOIOSVData { get; set; }
        public string NOIOSVText { get; set; }
        public decimal NOIOSVStatusID { get; set; }
    
        public virtual Pacient Pacient { get; set; }
    }
}
