//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NZOKAmbGrafik
    {
        public decimal NZOKAmbGrafikID { get; set; }
        public decimal PersonalID { get; set; }
        public decimal PersSpecID { get; set; }
        public decimal MedCentar { get; set; }
        public System.DateTime OtData { get; set; }
        public System.DateTime DoData { get; set; }
        public string AP1dt1 { get; set; }
        public string AP1dt2 { get; set; }
        public string AP2dt1 { get; set; }
        public string AP2dt2 { get; set; }
        public string AP3dt1 { get; set; }
        public string AP3dt2 { get; set; }
        public string AP4dt1 { get; set; }
        public string AP4dt2 { get; set; }
        public string AP5dt1 { get; set; }
        public string AP5dt2 { get; set; }
        public string AP6dt1 { get; set; }
        public string AP6dt2 { get; set; }
        public string AP7dt1 { get; set; }
        public string AP7dt2 { get; set; }
        public string DP1dt1 { get; set; }
        public string DP1dt2 { get; set; }
        public string DP2dt1 { get; set; }
        public string DP2dt2 { get; set; }
        public string DP3dt1 { get; set; }
        public string DP3dt2 { get; set; }
        public string DP4dt1 { get; set; }
        public string DP4dt2 { get; set; }
        public string DP5dt1 { get; set; }
        public string DP5dt2 { get; set; }
        public string DP6dt1 { get; set; }
        public string DP6dt2 { get; set; }
        public string DP7dt1 { get; set; }
        public string DP7dt2 { get; set; }
        public string PP1dt1 { get; set; }
        public string PP1dt2 { get; set; }
        public string PP2dt1 { get; set; }
        public string PP2dt2 { get; set; }
        public string PP3dt1 { get; set; }
        public string PP3dt2 { get; set; }
        public string PP4dt1 { get; set; }
        public string PP4dt2 { get; set; }
        public string PP5dt1 { get; set; }
        public string PP5dt2 { get; set; }
        public string PP6dt1 { get; set; }
        public string PP6dt2 { get; set; }
        public string PP7dt1 { get; set; }
        public string PP7dt2 { get; set; }
        public string EX1dt1 { get; set; }
        public string EX1dt2 { get; set; }
        public string EX2dt1 { get; set; }
        public string EX2dt2 { get; set; }
        public string EX3dt1 { get; set; }
        public string EX3dt2 { get; set; }
        public string EX4dt1 { get; set; }
        public string EX4dt2 { get; set; }
        public string EX5dt1 { get; set; }
        public string EX5dt2 { get; set; }
        public string EX6dt1 { get; set; }
        public string EX6dt2 { get; set; }
        public string EX7dt1 { get; set; }
        public string EX7dt2 { get; set; }
        public string VS1dt1 { get; set; }
        public string VS1dt2 { get; set; }
        public string VS2dt1 { get; set; }
        public string VS2dt2 { get; set; }
        public string VS3dt1 { get; set; }
        public string VS3dt2 { get; set; }
        public string VS4dt1 { get; set; }
        public string VS4dt2 { get; set; }
        public string VS5dt1 { get; set; }
        public string VS5dt2 { get; set; }
        public string VS6dt1 { get; set; }
        public string VS6dt2 { get; set; }
        public string VS7dt1 { get; set; }
        public string VS7dt2 { get; set; }
    
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
