//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NZOKAmbNorm
    {
        public decimal NZOKAmbNormID { get; set; }
        public System.DateTime OtData { get; set; }
        public System.DateTime DoData { get; set; }
        public Nullable<decimal> ApProd { get; set; }
        public Nullable<decimal> AvProd { get; set; }
        public Nullable<decimal> DpProd { get; set; }
        public Nullable<decimal> DvProd { get; set; }
        public Nullable<decimal> PpProd { get; set; }
        public Nullable<decimal> PvProd { get; set; }
        public Nullable<decimal> ExProd { get; set; }
        public Nullable<decimal> VsProd { get; set; }
    }
}
