//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocenki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ocenki()
        {
            this.BLOcenki = new HashSet<BLOcenki>();
        }
    
        public decimal OcID { get; set; }
        public string OcIme { get; set; }
        public short OcImageNo { get; set; }
        public Nullable<short> OcTochki { get; set; }
        public int OcSort { get; set; }
        public Nullable<System.DateTime> OcDoData { get; set; }
        public string OcPath { get; set; }
        public short OcLevel { get; set; }
        public Nullable<short> OcSumGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOcenki> BLOcenki { get; set; }
    }
}
