//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderData()
        {
            this.Order = new HashSet<Order>();
        }
    
        public decimal OrdDataId { get; set; }
        public decimal PacID { get; set; }
        public System.DateTime OrdDataData { get; set; }
        public string OrdDataSast { get; set; }
        public string OrdDataDrugi { get; set; }
        public string OrdDataProtokol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
