//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Antro_pok = new HashSet<Antro_pok>();
            this.OrderEntry = new HashSet<OrderEntry>();
            this.TabelaMedi = new HashSet<TabelaMedi>();
        }
    
        public decimal OrdId { get; set; }
        public decimal OrdDataId { get; set; }
        public decimal OrdNo { get; set; }
        public System.DateTime OrdData { get; set; }
        public decimal OrdKamOt { get; set; }
        public decimal OrdIF { get; set; }
        public Nullable<decimal> OrdDiag { get; set; }
        public decimal OrdTip { get; set; }
        public decimal OrdVZveno { get; set; }
        public decimal OrdOtZveno { get; set; }
        public decimal OrdLekar { get; set; }
        public string OrdDopDanni { get; set; }
        public string OrdFish { get; set; }
        public string OrdStaia { get; set; }
        public string OrdLeglo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antro_pok> Antro_pok { get; set; }
        public virtual OrderData OrderData { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Zveno Zveno1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEntry> OrderEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelaMedi> TabelaMedi { get; set; }
    }
}
