//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderEntry()
        {
            this.TabelaMediIzp = new HashSet<TabelaMediIzp>();
            this.Usluga = new HashSet<Usluga>();
        }
    
        public decimal OrdEId { get; set; }
        public decimal OrdId { get; set; }
        public Nullable<decimal> BolID { get; set; }
        public Nullable<decimal> PregledID { get; set; }
        public Nullable<decimal> ProID { get; set; }
        public Nullable<decimal> LabID { get; set; }
        public Nullable<decimal> FniID { get; set; }
        public Nullable<decimal> RodID { get; set; }
        public Nullable<decimal> OrderNomMedId { get; set; }
        public Nullable<decimal> OrdEVid { get; set; }
        public Nullable<decimal> OrdEVidMKB { get; set; }
        public Nullable<System.DateTime> OrdEDataMat { get; set; }
        public Nullable<decimal> OrdEVzelMat { get; set; }
        public Nullable<bool> OrdESp { get; set; }
        public Nullable<System.DateTime> OrdEZaIzp { get; set; }
        public string OrdEDopDanni { get; set; }
        public decimal OrdEStatus { get; set; }
        public Nullable<System.DateTime> OrdEIzpalneno { get; set; }
        public string OrdETip { get; set; }
        public string OrdELOINC { get; set; }
        public Nullable<decimal> OrdEVlagane { get; set; }
        public string OrdEKolichMedi { get; set; }
        public string OrdESignatura { get; set; }
        public string OrdEPril { get; set; }
        public string OrdELabVid { get; set; }
        public Nullable<System.DateTime> OrdEDataKrai { get; set; }
        public Nullable<decimal> OrdEChPriem { get; set; }
        public string OrdELLNo { get; set; }
        public Nullable<decimal> OrdEKol { get; set; }
        public Nullable<decimal> OrdELekar { get; set; }
        public Nullable<decimal> KPLechenieID { get; set; }
        public Nullable<decimal> OrdEMedCena { get; set; }
        public bool OrdEMedImport { get; set; }
        public Nullable<int> ordemodalityid { get; set; }
        public int PrescriptionNumber { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual IzsFNI IzsFNI { get; set; }
        public virtual IzsLAB IzsLAB { get; set; }
        public virtual IzsROD IzsROD { get; set; }
        public virtual Order Order { get; set; }
        public virtual PACSModality PACSModality { get; set; }
        public virtual OrderNomMed OrderNomMed { get; set; }
        public virtual Pregled Pregled { get; set; }
        public virtual Proceduri Proceduri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelaMediIzp> TabelaMediIzp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usluga> Usluga { get; set; }
    }
}
