//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSIOMD_IDS
    {
        public int ID { get; set; }
        public int ObjType { get; set; }
        public string ObjID { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> CD { get; set; }
    }
}
