//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSIOMD_EXTERNAL_ID
    {
        public int ID { get; set; }
        public int ObjID { get; set; }
        public int LocalID { get; set; }
        public string ExternalID { get; set; }
        public Nullable<System.DateTime> CD { get; set; }
    }
}
