//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacient()
        {
            this.AlertInfo = new HashSet<AlertInfo>();
            this.Antro_pok = new HashSet<Antro_pok>();
            this.Billing = new HashSet<Billing>();
            this.BolnichnoLechenie = new HashSet<BolnichnoLechenie>();
            this.DispDosie = new HashSet<DispDosie>();
            this.ExternalFiles = new HashSet<ExternalFiles>();
            this.Komitet = new HashSet<Komitet>();
            this.Konsultacia = new HashSet<Konsultacia>();
            this.MartvoRodeni = new HashSet<MartvoRodeni>();
            this.NOIProverka = new HashSet<NOIProverka>();
            this.NOIProverkaOSV = new HashSet<NOIProverkaOSV>();
            this.NovoRodeni = new HashSet<NovoRodeni>();
            this.Obsajdane = new HashSet<Obsajdane>();
            this.OrderData = new HashSet<OrderData>();
            this.toCypro = new HashSet<toCypro>();
            this.PlaniranePregled = new HashSet<PlaniranePregled>();
            this.Pochinali = new HashSet<Pochinali>();
            this.Pregled = new HashSet<Pregled>();
            this.TabelaMedi = new HashSet<TabelaMedi>();
            this.PregnancyRegister = new HashSet<PregnancyRegister>();
        }
    
        public decimal PacientID { get; set; }
        public System.DateTime PacDataNaRegistracia { get; set; }
        public string PacIme { get; set; }
        public string PacPrezime { get; set; }
        public string PacFamilia { get; set; }
        public string PacEGN { get; set; }
        public System.DateTime PacDataNaRajdane { get; set; }
        public bool PacIsENCh { get; set; }
        public bool PacIsJena { get; set; }
        public string PacAdres { get; set; }
        public string PacLicnaKarta { get; set; }
        public decimal PacGrajdanstvo { get; set; }
        public decimal PacDarjava { get; set; }
        public decimal PacJitelNa { get; set; }
        public Nullable<decimal> PacKravnaGrupa { get; set; }
        public bool PacIsVavJurnal { get; set; }
        public string PacArhivenNomer { get; set; }
        public string PacJurnalenNomer { get; set; }
        public bool PacIsZakluchen { get; set; }
        public decimal PacMiastoNaReg { get; set; }
        public Nullable<decimal> PacZOO { get; set; }
        public string PacLicenZdravnoOsigNomer { get; set; }
        public Nullable<decimal> PacOblast { get; set; }
        public Nullable<decimal> PacObstina { get; set; }
        public Nullable<decimal> PacRZOK { get; set; }
        public Nullable<decimal> PacZdravenRaion { get; set; }
        public string PacTelDomashen { get; set; }
        public string PacTelSlujeben { get; set; }
        public string PacTelFaks { get; set; }
        public string PacTelMobilen { get; set; }
        public string PacPager { get; set; }
        public string PacEmail { get; set; }
        public Nullable<decimal> PacSemeinoPolojenie { get; set; }
        public Nullable<decimal> PacObrazovanie { get; set; }
        public string PacMestorabota { get; set; }
        public string PacLicaZaKontakt { get; set; }
        public bool PacIsVIP { get; set; }
        public bool PacIsDarjavnaZOO { get; set; }
        public bool PacIsVunshen { get; set; }
        public Nullable<decimal> PacMaikaID { get; set; }
        public string PacGrad { get; set; }
        public string PacPID { get; set; }
        public Nullable<decimal> PacSocGr { get; set; }
        public string PacOrgOsig { get; set; }
        public Nullable<decimal> PacVidOD { get; set; }
        public Nullable<System.DateTime> PacDataOD { get; set; }
        public Nullable<System.DateTime> PacODOt { get; set; }
        public Nullable<System.DateTime> PacODDo { get; set; }
        public string PacEZOKNo { get; set; }
        public string PacPONo { get; set; }
        public Nullable<bool> PacZOES { get; set; }
        public string PacOrgOsigIme { get; set; }
        public string PacOsiguren { get; set; }
        public bool PacZOsiguren { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertInfo> AlertInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antro_pok> Antro_pok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispDosie> DispDosie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalFiles> ExternalFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komitet> Komitet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konsultacia> Konsultacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MartvoRodeni> MartvoRodeni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIProverka> NOIProverka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIProverkaOSV> NOIProverkaOSV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NovoRodeni> NovoRodeni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obsajdane> Obsajdane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderData> OrderData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toCypro> toCypro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaniranePregled> PlaniranePregled { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pochinali> Pochinali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregled> Pregled { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelaMedi> TabelaMedi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PregnancyRegister> PregnancyRegister { get; set; }
    }
}
