//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACSACKLog
    {
        public decimal ACKId { get; set; }
        public System.DateTime ACKDTR { get; set; }
        public string ACKVid { get; set; }
        public System.DateTime ACKDTM { get; set; }
        public string ACKTip { get; set; }
        public decimal ACKMCId { get; set; }
        public string ACKKod { get; set; }
        public string ACKDopDanni { get; set; }
    }
}
