//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pauza
    {
        public decimal PauzaID { get; set; }
        public Nullable<decimal> ZvenoID { get; set; }
        public System.DateTime PauzaOt { get; set; }
        public System.DateTime PauzaDo { get; set; }
    
        public virtual Zveno Zveno { get; set; }
    }
}
