//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalRS2
    {
        public decimal RS2Id { get; set; }
        public decimal RS1Id { get; set; }
        public Nullable<decimal> RS2Napr3 { get; set; }
        public Nullable<decimal> RS2Napr3Broi { get; set; }
        public Nullable<decimal> RS2Napr3A { get; set; }
        public Nullable<decimal> RS2Napr3ABroi { get; set; }
        public Nullable<decimal> RS2Napr4 { get; set; }
        public Nullable<decimal> RS2Napr4Suma { get; set; }
        public Nullable<decimal> RS2DispBroi { get; set; }
    
        public virtual PersonalRS1 PersonalRS1 { get; set; }
    }
}
