//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalRS1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalRS1()
        {
            this.PersonalRS2 = new HashSet<PersonalRS2>();
        }
    
        public decimal RS1Id { get; set; }
        public decimal PersonalID { get; set; }
        public decimal RS1Spec { get; set; }
        public decimal RS1Dog { get; set; }
        public System.DateTime RS1OtData { get; set; }
        public System.DateTime RS1DoData { get; set; }
    
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalRS2> PersonalRS2 { get; set; }
    }
}
