//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalPC
    {
        public decimal PCId { get; set; }
        public decimal PCDogovorID { get; set; }
        public decimal PCPersonalID { get; set; }
        public decimal PCPersonalSpec { get; set; }
        public Nullable<decimal> PCNapr3 { get; set; }
        public Nullable<decimal> PCNapr3A { get; set; }
        public Nullable<decimal> PCNapr4 { get; set; }
        public Nullable<decimal> PCNapr3Tip4 { get; set; }
        public Nullable<decimal> PCNapr3ATip4 { get; set; }
        public Nullable<decimal> PCNapr4Tip4 { get; set; }
        public Nullable<decimal> PCDisp { get; set; }
        public decimal PCNapr4Tip9 { get; set; }
    
        public virtual DogovorPC DogovorPC { get; set; }
    }
}
