//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalZveno
    {
        public decimal PersonalZvenoID { get; set; }
        public decimal PersonalID { get; set; }
        public decimal ZvenoID { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Zveno Zveno { get; set; }
    }
}
