//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaniranePregled
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaniranePregled()
        {
            this.BolnichnoLechenie = new HashSet<BolnichnoLechenie>();
            this.KpLechenie = new HashSet<KpLechenie>();
            this.Pregled = new HashSet<Pregled>();
        }
    
        public decimal PlaniranePregledID { get; set; }
        public decimal PacientID { get; set; }
        public decimal ZvenoID { get; set; }
        public System.DateTime PlanPrData { get; set; }
        public Nullable<decimal> PlanZap { get; set; }
        public Nullable<bool> PlanPrIsPlaniran { get; set; }
        public Nullable<bool> PlanPrIsSpeshen { get; set; }
        public Nullable<int> PlanIsPriem { get; set; }
        public Nullable<bool> PlanIsIzpalneno { get; set; }
        public Nullable<bool> PlanIsDublirano { get; set; }
        public string PlanBelejki { get; set; }
        public Nullable<decimal> PlanTip { get; set; }
        public Nullable<decimal> PlanLekar { get; set; }
        public bool PlanTalon { get; set; }
        public Nullable<long> PlanCounter { get; set; }
        public bool IsApr { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string ConfirmationDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolnichnoLechenie> BolnichnoLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KpLechenie> KpLechenie { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Zveno Zveno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregled> Pregled { get; set; }
    }
}
