//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaniraneOper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaniraneOper()
        {
            this.Antro_pok = new HashSet<Antro_pok>();
        }
    
        public decimal POID { get; set; }
        public decimal ObsID { get; set; }
        public decimal POZa { get; set; }
        public System.DateTime POData { get; set; }
        public decimal POProc { get; set; }
        public string POProcDop { get; set; }
        public decimal POMiasto { get; set; }
        public Nullable<bool> POSpeshna { get; set; }
        public Nullable<bool> POEKK { get; set; }
        public string POKokKrav { get; set; }
        public string PONeobMat { get; set; }
        public string PONeoIzsl { get; set; }
        public Nullable<System.DateTime> PODataIzsl { get; set; }
        public Nullable<System.DateTime> PODataOP { get; set; }
        public Nullable<bool> POAnul { get; set; }
        public string POPrIzkl { get; set; }
        public Nullable<decimal> POEuroScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antro_pok> Antro_pok { get; set; }
        public virtual Zveno Zveno { get; set; }
    }
}
