//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PochinaliTakDonori
    {
        public decimal PocTDID { get; set; }
        public decimal PochinalID { get; set; }
        public System.DateTime PocTDData { get; set; }
        public decimal PocTDVid { get; set; }
        public decimal PocTDBanka { get; set; }
    
        public virtual Pochinali Pochinali { get; set; }
    }
}
