//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregled
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregled()
        {
            this.Antro_pok = new HashSet<Antro_pok>();
            this.BList = new HashSet<BList>();
            this.IzdNaprNZOK = new HashSet<IzdNaprNZOK>();
            this.OrderEntry = new HashSet<OrderEntry>();
            this.Pochinali = new HashSet<Pochinali>();
            this.PregledDiagnoza = new HashSet<PregledDiagnoza>();
            this.SpeshenList = new HashSet<SpeshenList>();
            this.TabelaMedi = new HashSet<TabelaMedi>();
        }
    
        public decimal PregledID { get; set; }
        public decimal PacientID { get; set; }
        public System.DateTime PregledData { get; set; }
        public decimal PregledMiasto { get; set; }
        public decimal PregledLekar { get; set; }
        public Nullable<decimal> PregledSestra { get; set; }
        public string PregledKonsultant { get; set; }
        public string PregledVanKonsultant { get; set; }
        public decimal PregledVid { get; set; }
        public Nullable<decimal> PregledFinans { get; set; }
        public Nullable<decimal> PregledNasOt { get; set; }
        public Nullable<decimal> PregledNasS { get; set; }
        public string PregledNasLekar { get; set; }
        public Nullable<System.DateTime> PregledNasData { get; set; }
        public string PregledNasBelejki { get; set; }
        public string PregledAnamneza { get; set; }
        public Nullable<decimal> PregledTemperaturaAx { get; set; }
        public Nullable<decimal> PregledTemperaturaRt { get; set; }
        public Nullable<decimal> PregledSNaliagane { get; set; }
        public Nullable<decimal> PregledDNaliagane { get; set; }
        public Nullable<decimal> PregledSardecna { get; set; }
        public Nullable<decimal> PregledPuls { get; set; }
        public string PregledFizikal { get; set; }
        public Nullable<decimal> PregledDiagID { get; set; }
        public string PregledDiagNote { get; set; }
        public string PregledZakluchenie { get; set; }
        public string PregledKrai { get; set; }
        public Nullable<decimal> PregledUslugaID { get; set; }
        public Nullable<decimal> PlanPregledID { get; set; }
        public string PregledKonsult { get; set; }
        public string PregledNasDok { get; set; }
        public Nullable<decimal> PregledMedCentar { get; set; }
        public Nullable<bool> PregledIsDisp { get; set; }
        public Nullable<bool> PregledIsNeotl { get; set; }
        public Nullable<bool> PregledIsSpPom { get; set; }
        public Nullable<bool> PregledIsProfil { get; set; }
        public Nullable<bool> PregledIsKonsult { get; set; }
        public string PregledStatus { get; set; }
        public string PregledTerapia { get; set; }
        public Nullable<decimal> BolID { get; set; }
        public Nullable<decimal> DispDosieID { get; set; }
        public Nullable<decimal> PregledZapl { get; set; }
        public string PregledMC { get; set; }
        public string PregledRP { get; set; }
        public string PregledRecepta { get; set; }
        public Nullable<System.DateTime> PregledDataKrai { get; set; }
        public Nullable<decimal> PregledIzhod { get; set; }
        public Nullable<decimal> KpLechenieID { get; set; }
        public string UslugiList { get; set; }
        public Nullable<decimal> PregnacyRegisterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antro_pok> Antro_pok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BList> BList { get; set; }
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual DispDosie DispDosie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzdNaprNZOK> IzdNaprNZOK { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Nomenklatura Nomenklatura2 { get; set; }
        public virtual Nomenklatura Nomenklatura3 { get; set; }
        public virtual Nomenklatura Nomenklatura4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEntry> OrderEntry { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Personal Personal1 { get; set; }
        public virtual PlaniranePregled PlaniranePregled { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pochinali> Pochinali { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Zveno Zveno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PregledDiagnoza> PregledDiagnoza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeshenList> SpeshenList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelaMedi> TabelaMedi { get; set; }
        public virtual PregnancyRegister PregnancyRegister { get; set; }
    }
}
