//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PregnancyRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PregnancyRegister()
        {
            this.Pregled = new HashSet<Pregled>();
        }
    
        public decimal Pregnancy_Register_Id { get; set; }
        public System.DateTime Registration_Date { get; set; }
        public decimal Doctor_Id { get; set; }
        public decimal Patient_Id { get; set; }
        public decimal MedInstitution { get; set; }
        public decimal Ambulatory_Visit_Number { get; set; }
        public decimal Diagnosis_Id { get; set; }
        public Nullable<System.DateTime> Unregister_Date { get; set; }
        public Nullable<decimal> Unregister_Reason { get; set; }
        public System.DateTime Last_Period_Date { get; set; }
        public Nullable<decimal> Risk_Pregnancy_Type { get; set; }
    
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregled> Pregled { get; set; }
    }
}
