//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PregledDiagnoza
    {
        public decimal PregledDiagID { get; set; }
        public decimal PregledID { get; set; }
        public decimal DiagID { get; set; }
        public string DiagTip { get; set; }
        public string DiagDop { get; set; }
    
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Pregled Pregled { get; set; }
    }
}
