//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prevejdane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prevejdane()
        {
            this.IntLechenie = new HashSet<IntLechenie>();
        }
    
        public decimal PrevejdaneID { get; set; }
        public decimal BolID { get; set; }
        public System.DateTime PrevData { get; set; }
        public decimal PrevMiasto { get; set; }
        public string PrevStaia { get; set; }
        public string PrevLeglo { get; set; }
        public string PrevDrugi { get; set; }
        public bool PrevIsVip { get; set; }
        public Nullable<decimal> Leglodni { get; set; }
        public string Protokol { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntLechenie> IntLechenie { get; set; }
        public virtual Zveno Zveno { get; set; }
    }
}
