//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceduri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proceduri()
        {
            this.Implantant = new HashSet<Implantant>();
            this.IzdNaprNZOK = new HashSet<IzdNaprNZOK>();
            this.OrderEntry = new HashSet<OrderEntry>();
        }
    
        public decimal ProID { get; set; }
        public System.DateTime ProDataChas { get; set; }
        public Nullable<System.DateTime> ProProd { get; set; }
        public decimal ProKamOtch { get; set; }
        public string ProNo { get; set; }
        public decimal ProFinans { get; set; }
        public Nullable<decimal> ProVid { get; set; }
        public string ProDopDanni { get; set; }
        public Nullable<decimal> ProMKB { get; set; }
        public string ProMKBDop { get; set; }
        public decimal ProMiasto { get; set; }
        public decimal ProLekar { get; set; }
        public bool ProSpeshno { get; set; }
        public bool ProAmbList { get; set; }
        public Nullable<decimal> ProNasZveno { get; set; }
        public Nullable<decimal> ProNasVun { get; set; }
        public string ProNasDoc { get; set; }
        public Nullable<System.DateTime> ProNasData { get; set; }
        public Nullable<decimal> ProNasDiag { get; set; }
        public string ProNasDrugi { get; set; }
        public decimal ProDiag { get; set; }
        public Nullable<decimal> ProDiagDop { get; set; }
        public string ProDopDiag { get; set; }
        public string ProDrugi { get; set; }
        public string ProZak { get; set; }
        public bool ProProfilakt { get; set; }
        public bool ProDispanser { get; set; }
        public string ProProtSave { get; set; }
        public decimal PacID { get; set; }
        public Nullable<decimal> BolID { get; set; }
        public Nullable<System.DateTime> ProDataChasKrai { get; set; }
        public string ProProtRes { get; set; }
        public Nullable<decimal> KpLechenieID { get; set; }
    
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Diagnoza Diagnoza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Implantant> Implantant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzdNaprNZOK> IzdNaprNZOK { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
        public virtual Nomenklatura Nomenklatura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEntry> OrderEntry { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Usluga Usluga { get; set; }
        public virtual Zveno Zveno { get; set; }
        public virtual Zveno Zveno1 { get; set; }
    }
}
