//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazhodTip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RazhodTip()
        {
            this.RazhodTipActivities = new HashSet<RazhodTipActivities>();
            this.WeightedCalculationByEventAndUnit = new HashSet<WeightedCalculationByEventAndUnit>();
        }
    
        public decimal RazhodTipID { get; set; }
        public string RTKey { get; set; }
        public string RTIme { get; set; }
        public string RTZvena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RazhodTipActivities> RazhodTipActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightedCalculationByEventAndUnit> WeightedCalculationByEventAndUnit { get; set; }
    }
}
