//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazhodTipActivities
    {
        public decimal Id { get; set; }
        public decimal RazhodTipId { get; set; }
        public Nullable<decimal> UslugaId { get; set; }
        public Nullable<decimal> ProcedureId { get; set; }
        public Nullable<double> Coefficient { get; set; }
    
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual RazhodTip RazhodTip { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
