//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razhodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Razhodi()
        {
            this.Razhod_Transfer_Zvena = new HashSet<Razhod_Transfer_Zvena>();
            this.WeightedCalculationByEventAndUnit = new HashSet<WeightedCalculationByEventAndUnit>();
        }
    
        public decimal RazhodiID { get; set; }
        public Nullable<System.DateTime> KROtData { get; set; }
        public Nullable<System.DateTime> KRDoData { get; set; }
        public Nullable<decimal> KRSrRazhodLekar { get; set; }
        public Nullable<decimal> KRVnKRazhod { get; set; }
        public Nullable<decimal> KRSebOper { get; set; }
        public Nullable<decimal> KRSebVtKons { get; set; }
        public Nullable<decimal> KRSebVnKons { get; set; }
        public Nullable<decimal> KRSebLab { get; set; }
        public Nullable<decimal> KRSebFNI { get; set; }
        public Nullable<decimal> KRSebROD { get; set; }
        public Nullable<decimal> KRSebDII { get; set; }
        public Nullable<decimal> KRSebEFI { get; set; }
        public Nullable<decimal> KRSebPro { get; set; }
        public Nullable<decimal> KRSebVSI { get; set; }
        public Nullable<decimal> KRSebPregled { get; set; }
        public Nullable<decimal> KRSebAutopsia { get; set; }
        public Nullable<decimal> KRKoefMOper { get; set; }
        public Nullable<decimal> KRKoefSOper { get; set; }
        public Nullable<decimal> KRKoefGOper { get; set; }
        public Nullable<decimal> KRKoefOOper { get; set; }
        public Nullable<decimal> KRKoefVtKons { get; set; }
        public Nullable<decimal> KRKoefROD { get; set; }
        public Nullable<decimal> KRKoefIP { get; set; }
        public Nullable<decimal> KRKoefEFI { get; set; }
        public Nullable<decimal> KRKoefFNI { get; set; }
        public Nullable<decimal> KRBroiLekari { get; set; }
        public Nullable<decimal> KRSebHemo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Razhod_Transfer_Zvena> Razhod_Transfer_Zvena { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightedCalculationByEventAndUnit> WeightedCalculationByEventAndUnit { get; set; }
    }
}
