//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razhod_Transfer
    {
        public decimal RTId { get; set; }
        public decimal RTTip { get; set; }
        public decimal RTBolID { get; set; }
        public string RTIZNo { get; set; }
        public decimal RTStatus1 { get; set; }
        public System.DateTime RTDataZ { get; set; }
        public Nullable<System.DateTime> RTDataBA { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
    }
}
