//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razhod_Transfer_Zvena
    {
        public decimal RZID { get; set; }
        public decimal RZRazhodiID { get; set; }
        public decimal RZTip { get; set; }
        public System.DateTime RZTData { get; set; }
    
        public virtual Razhodi Razhodi { get; set; }
    }
}
