//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazZveno
    {
        public decimal RazZvenoID { get; set; }
        public decimal RazhodiID { get; set; }
        public string RazZvenoKod { get; set; }
        public decimal RazZvenoSuma { get; set; }
        public decimal RazZvenoSrRazLegloden { get; set; }
        public decimal RazZvenoLeglodni { get; set; }
    }
}
