//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recepta()
        {
            this.ReceptaMed = new HashSet<ReceptaMed>();
        }
    
        public decimal RecId { get; set; }
        public decimal AmbListID { get; set; }
        public string RecVid { get; set; }
        public decimal RecNo { get; set; }
        public System.DateTime RecData { get; set; }
        public string RecProtNo { get; set; }
        public Nullable<System.DateTime> RecProtData { get; set; }
        public string RecKnNo { get; set; }
        public Nullable<bool> RecBrem { get; set; }
        public Nullable<bool> RecKarm { get; set; }
        public Nullable<bool> RecAnul { get; set; }
    
        public virtual AmbList2005 AmbList2005 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceptaMed> ReceptaMed { get; set; }
    }
}
