//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptaMed
    {
        public decimal RecMedId { get; set; }
        public decimal RecId { get; set; }
        public decimal RecMedVid { get; set; }
        public string RecMedRp { get; set; }
        public decimal RecMedDiag { get; set; }
        public decimal RecMedKol { get; set; }
        public decimal RecMedBroiDni { get; set; }
    
        public virtual Recepta Recepta { get; set; }
    }
}
