//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptaMedSpisak
    {
        public decimal PLSId { get; set; }
        public string PLSATCKod { get; set; }
        public string PLSTargovsko { get; set; }
        public string PLSForma { get; set; }
        public string PLSKolAkt { get; set; }
        public string PLSMiarka { get; set; }
        public string PLSOpakovka { get; set; }
        public string PLSDopDanni { get; set; }
        public string PLSKodNZOK { get; set; }
        public Nullable<decimal> PLSZapl { get; set; }
        public bool PLSNevidim { get; set; }
        public Nullable<System.DateTime> PLSDoData { get; set; }
    }
}
