//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionSelect
    {
        public decimal OBID { get; set; }
        public string OBName { get; set; }
        public decimal RZOKID { get; set; }
        public string RZOKName { get; set; }
    }
}
