//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportForm3Sp
    {
        public decimal F3Id { get; set; }
        public string F3DiagGroup { get; set; }
        public int F3GroupNo { get; set; }
        public string F3DiagOt { get; set; }
        public string F3DiagDo { get; set; }
    }
}
