//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_5B1_2005_1
    {
        public decimal R53Id { get; set; }
        public string R53Klas { get; set; }
        public string R53DiagIme { get; set; }
        public decimal R53Shifar { get; set; }
        public string R53DiagCode { get; set; }
        public Nullable<bool> R53FLevel { get; set; }
        public string R53Code1 { get; set; }
        public string R53Code2 { get; set; }
    }
}
