//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_5_2008_1
    {
        public decimal R5Id { get; set; }
        public string R5Klas { get; set; }
        public string R5DiagIme { get; set; }
        public decimal R5Shifar { get; set; }
        public string R5DiagCode { get; set; }
        public Nullable<bool> R5FLevel { get; set; }
        public string R5Code1 { get; set; }
        public string R5Code2 { get; set; }
        public Nullable<int> R5Group { get; set; }
        public Nullable<int> R5Sort { get; set; }
    }
}
