//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_6B
    {
        public decimal R6B_AUTO { get; set; }
        public string R6BDIAGNAME { get; set; }
        public decimal R6BSHIFAR { get; set; }
        public string R6BDIAGCODE { get; set; }
        public bool R6BFLEVEL { get; set; }
        public string R6BDCode1 { get; set; }
        public string R6BDCode2 { get; set; }
    }
}
