//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_KDKK1
    {
        public decimal RK_Id { get; set; }
        public string RK_DiagGroup { get; set; }
        public string RK_GroupNo { get; set; }
        public string RK_DiagOt { get; set; }
        public string RK_DiagDo { get; set; }
    }
}
