//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_GOD_4_1
    {
        public decimal GOD41_AUTO { get; set; }
        public string GOD41_OPISANIE { get; set; }
        public Nullable<decimal> GOD41_N1ID { get; set; }
        public Nullable<decimal> GOD41_N2ID { get; set; }
        public decimal GOD41_SHIFAR { get; set; }
    }
}
