//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_365_3
    {
        public decimal R3_Id { get; set; }
        public string R3_DiagIme { get; set; }
        public string R3_DiagTip { get; set; }
        public string R3_DiagShifar { get; set; }
        public string R3_MKB10 { get; set; }
        public string R3_Kod1 { get; set; }
        public string R3_Kod2 { get; set; }
    }
}
