//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_5B_2005_2
    {
        public decimal R52Id { get; set; }
        public string R52Klas { get; set; }
        public string R52DiagIme { get; set; }
        public decimal R52Shifar { get; set; }
        public string R52DiagCode { get; set; }
        public Nullable<bool> R52FLevel { get; set; }
        public string R52Code1 { get; set; }
        public string R52Code2 { get; set; }
    }
}
