//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_365_5
    {
        public decimal R5_Id { get; set; }
        public string R5_OtdVid { get; set; }
        public string R5_MedNapr { get; set; }
        public string R5_Shifar { get; set; }
    }
}
