//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_F14
    {
        public decimal F14Id { get; set; }
        public string F14KlasIme { get; set; }
        public string F14KlasNomer { get; set; }
        public string F14DiagOt { get; set; }
        public string F14DiagDo { get; set; }
    }
}
