//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_365_2012_1
    {
        public decimal R7_Id { get; set; }
        public string R7_PersVid { get; set; }
        public string R7_Spec { get; set; }
        public string Rt_Shifar { get; set; }
        public Nullable<decimal> RT_PostID { get; set; }
    }
}
