//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_YS
    {
        public decimal R51Id { get; set; }
        public string R51Klas { get; set; }
        public string R51DiagIme { get; set; }
        public decimal R51Shifar { get; set; }
        public string R51DiagCode { get; set; }
        public Nullable<bool> R51FLevel { get; set; }
        public string R51Code1 { get; set; }
        public string R51Code2 { get; set; }
    }
}
