//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports78
    {
        public int RP78RowID { get; set; }
        public string RP78DiagIme { get; set; }
        public Nullable<int> RP78Ot { get; set; }
        public Nullable<int> Rp78Do { get; set; }
        public bool Rp78Level { get; set; }
        public Nullable<int> Rp78LevNo { get; set; }
    }
}
