//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_365_2
    {
        public decimal R2_Id { get; set; }
        public string R2_OperIme { get; set; }
        public string R2_OperShifar { get; set; }
        public string R2_OperMKB { get; set; }
        public Nullable<bool> R2_Level { get; set; }
        public string R2_Kod1 { get; set; }
        public string R2_Kod2 { get; set; }
    }
}
