//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_365_2012_4
    {
        public decimal DO_ID { get; set; }
        public string DO_Group { get; set; }
        public string DO_Shifar { get; set; }
        public string DO_Code1 { get; set; }
        public string DO_Code2 { get; set; }
        public Nullable<bool> DO_Level { get; set; }
    }
}
