//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_365_6A
    {
        public decimal R6_Id { get; set; }
        public string R6_Otd_Vid { get; set; }
        public Nullable<decimal> R6_OtID { get; set; }
        public Nullable<decimal> R6_DoID { get; set; }
        public string R6_Shifar { get; set; }
    }
}
