//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_5B_2006_1
    {
        public decimal R521Id { get; set; }
        public string R521Klas { get; set; }
        public string R521DiagIme { get; set; }
        public decimal R521Shifar { get; set; }
        public string R521DiagCode { get; set; }
        public Nullable<bool> R521FLevel { get; set; }
        public string R521Code1 { get; set; }
        public string R521Code2 { get; set; }
    }
}
