//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_GOD_3_Old
    {
        public decimal GOD3_AUTO { get; set; }
        public string GOD3_OPISANIE { get; set; }
        public string GOD3_Spec { get; set; }
        public string GOD3_SHIFAR { get; set; }
    }
}
