//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_God_LAB
    {
        public decimal IL_Id { get; set; }
        public string IL_Group { get; set; }
        public string IL_Shifar { get; set; }
        public string IL_Code1 { get; set; }
        public string IL_Code2 { get; set; }
        public Nullable<bool> IL_Level { get; set; }
    }
}
