//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_5B2_2005_2
    {
        public decimal R56Id { get; set; }
        public string R56Klas { get; set; }
        public string R56DiagIme { get; set; }
        public decimal R56Shifar { get; set; }
        public string R56DiagCode { get; set; }
        public Nullable<bool> R56FLevel { get; set; }
        public string R56Code1 { get; set; }
        public string R56Code2 { get; set; }
    }
}
