//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_5B1_2005_2
    {
        public decimal R54Id { get; set; }
        public string R54Klas { get; set; }
        public string R54DiagIme { get; set; }
        public decimal R54Shifar { get; set; }
        public string R54DiagCode { get; set; }
        public Nullable<bool> R54FLevel { get; set; }
        public string R54Code1 { get; set; }
        public string R54Code2 { get; set; }
    }
}
