//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_God_FIS_Old
    {
        public decimal FIS_ID { get; set; }
        public string FIS_Group { get; set; }
        public string FIS_Shifar { get; set; }
        public string FIS_Code1 { get; set; }
        public string FIS_Code2 { get; set; }
        public Nullable<bool> FIS_Level { get; set; }
    }
}
