//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTimeInterval
    {
        public int ID { get; set; }
        public int ScheduleID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int DayOfTheWeek { get; set; }
        public Nullable<int> ExaminationType { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsPrivate { get; set; }
    
        public virtual DoctorsSchedule DoctorsSchedule { get; set; }
    }
}
