//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Log
    {
        public decimal LogID { get; set; }
        public Nullable<decimal> ModuleID { get; set; }
        public string Computer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Operation { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> Pac_Key { get; set; }
    }
}
