//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedBLfieldsForDRG
    {
        public decimal ID { get; set; }
        public decimal BLPacID { get; set; }
        public string BLIZNo { get; set; }
        public Nullable<decimal> BLNasOt { get; set; }
        public Nullable<bool> BLHasDogNZOK { get; set; }
        public Nullable<decimal> BLNasRZOKNo { get; set; }
        public Nullable<decimal> BLNasZdrRaion { get; set; }
        public Nullable<decimal> BLNasZavRegNo { get; set; }
        public string BLNasEGNLekar { get; set; }
        public string BLNasLekarIme { get; set; }
        public Nullable<bool> BLNasIsSpeshen { get; set; }
        public string BLNasKliPat { get; set; }
        public Nullable<decimal> BLNasDiag1 { get; set; }
        public Nullable<decimal> BLNasDiagDop1 { get; set; }
        public Nullable<decimal> BLNasDiag2 { get; set; }
        public Nullable<decimal> BLNasDiagDop2 { get; set; }
        public Nullable<System.DateTime> BLDatIzprashtane { get; set; }
        public System.DateTime BLDataChas { get; set; }
        public Nullable<bool> BLIsSpeshen { get; set; }
        public Nullable<decimal> BLKliPat { get; set; }
        public Nullable<decimal> BLLekarID { get; set; }
        public decimal BLDiag1 { get; set; }
        public Nullable<decimal> BLDiagDop1 { get; set; }
        public Nullable<decimal> BLDiag2 { get; set; }
        public Nullable<decimal> BLDiagDop2 { get; set; }
        public string BLStepenTej { get; set; }
        public Nullable<decimal> BLVremeOtNach { get; set; }
        public Nullable<System.DateTime> BLNapDataChas { get; set; }
        public Nullable<short> BLNapDetDni { get; set; }
        public Nullable<short> BLNapDetGram { get; set; }
        public Nullable<int> BLNapMamIZN { get; set; }
        public Nullable<short> BLNapMamGod { get; set; }
        public Nullable<decimal> BLNapOkDiag { get; set; }
        public Nullable<decimal> BLNapOkDiagDop { get; set; }
        public Nullable<decimal> BLNapDopDiag1 { get; set; }
        public Nullable<decimal> BLNapDopDiag2 { get; set; }
        public Nullable<decimal> BLNapDopDiag3 { get; set; }
        public Nullable<decimal> BLNapDopDiag4 { get; set; }
        public Nullable<decimal> BLNapDopDiag5 { get; set; }
        public Nullable<decimal> BLNapUslojnenie { get; set; }
        public Nullable<decimal> BLNapStatus { get; set; }
        public Nullable<bool> BLNapOtkazal { get; set; }
        public Nullable<decimal> BLNapPreBolnica { get; set; }
        public Nullable<decimal> BLNapPreDiag { get; set; }
        public Nullable<decimal> BLNapPreDiagDop { get; set; }
        public Nullable<decimal> BLNapSustoianie { get; set; }
        public Nullable<decimal> BLNapOtdel { get; set; }
        public string BLNapPrePrich { get; set; }
        public Nullable<System.DateTime> BlParviPregled { get; set; }
        public Nullable<decimal> BLNapKliPat { get; set; }
        public Nullable<decimal> BLNapLekar { get; set; }
        public Nullable<decimal> BLNapZavLekar { get; set; }
    }
}
