//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shablon1
    {
        public decimal ShId { get; set; }
        public bool ShBL { get; set; }
        public decimal ShBLId { get; set; }
        public string ShTablica { get; set; }
        public string ShPole { get; set; }
        public string ShDiagOt { get; set; }
        public string ShDiagDo { get; set; }
        public string ShText { get; set; }
        public string ShComent { get; set; }
    }
}
