//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shablon2
    {
        public decimal S2ID { get; set; }
        public string S2Event { get; set; }
        public string S2Ime { get; set; }
        public string S2Text { get; set; }
        public bool S2Invisible { get; set; }
        public string S2FileZveno { get; set; }
    }
}
