//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sluchai
    {
        public decimal SluID { get; set; }
        public decimal SluSreID { get; set; }
        public decimal SluPacID { get; set; }
        public string SluDokladval { get; set; }
        public string SluAnaliz { get; set; }
        public string SluIzvodi { get; set; }
        public string SluRezultat { get; set; }
        public string SluNasochen { get; set; }
    
        public virtual Sreshti Sreshti { get; set; }
    }
}
