//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialnostPersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecialnostPersonal()
        {
            this.Personal = new HashSet<Personal>();
            this.SpecialnostPersonal1 = new HashSet<SpecialnostPersonal>();
        }
    
        public decimal SpecialnostPersonalID { get; set; }
        public Nullable<decimal> SpecialnostPersonalSelfID { get; set; }
        public string SpecPersIme { get; set; }
        public string SpecPersKod { get; set; }
        public bool SpecPersIsZaLekar { get; set; }
        public bool SpecPersKabinet { get; set; }
        public bool SpecPersKlinika { get; set; }
        public bool SpecPersMDZ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialnostPersonal> SpecialnostPersonal1 { get; set; }
        public virtual SpecialnostPersonal SpecialnostPersonal2 { get; set; }
    }
}
