//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeshenListDop
    {
        public decimal SpListDopID { get; set; }
        public decimal SpListID { get; set; }
        public decimal PregledID { get; set; }
        public Nullable<System.DateTime> K1Naz { get; set; }
        public Nullable<System.DateTime> K1Exc { get; set; }
        public string K1Spec { get; set; }
        public string K1Rez { get; set; }
        public Nullable<System.DateTime> K2Naz { get; set; }
        public Nullable<System.DateTime> K2Exc { get; set; }
        public string K2Spec { get; set; }
        public string K2Rez { get; set; }
        public Nullable<System.DateTime> K3Naz { get; set; }
        public Nullable<System.DateTime> K3Exc { get; set; }
        public string K3Spec { get; set; }
        public string K3Rez { get; set; }
        public Nullable<System.DateTime> K4Naz { get; set; }
        public Nullable<System.DateTime> K4Exp { get; set; }
        public string K4Spec { get; set; }
        public string K4Rez { get; set; }
    }
}
