//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpravkaAjurGod
    {
        public decimal SAId { get; set; }
        public string SAGodina { get; set; }
        public string SAAjurID { get; set; }
    }
}
