//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spravka
    {
        public decimal SpravkaID { get; set; }
        public Nullable<decimal> SpravkaSelfID { get; set; }
        public string SpravkaIme { get; set; }
        public string SpravkaTag { get; set; }
        public decimal SpravkaSort { get; set; }
        public bool SpravkaInvisible { get; set; }
        public string SpravkaBolnica { get; set; }
        public string SpravkaSecModule { get; set; }
        public string SpravkaHelp { get; set; }
        public bool SpravkaIsE { get; set; }
        public string XSDName { get; set; }
    }
}
