//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpravkaFav
    {
        public decimal SFId { get; set; }
        public string SFUserName { get; set; }
        public string SFTag { get; set; }
        public System.DateTime SFData { get; set; }
        public decimal SFCount { get; set; }
    }
}
