//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempletFile
    {
        public decimal TempletFileID { get; set; }
        public string TempletFileSpec { get; set; }
        public string TempletFileName { get; set; }
        public string TempletFileZveno { get; set; }
        public decimal EventType { get; set; }
        public Nullable<decimal> TempletFileOrder { get; set; }
        public Nullable<bool> TemplatePrint { get; set; }
    }
}
