//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpMedNzok
    {
        public string NzokCode { get; set; }
        public string ATC { get; set; }
        public string INN { get; set; }
        public string Name { get; set; }
        public string Form { get; set; }
        public string ActiveQty { get; set; }
        public string UOM { get; set; }
        public decimal FinalQty { get; set; }
        public decimal Qty { get; set; }
        public string LicenseHolder { get; set; }
        public decimal Price { get; set; }
        public int Mode { get; set; }
        public int PaymentRule { get; set; }
        public bool PainKiller { get; set; }
        public string MKB { get; set; }
        public Nullable<int> ClaimRule { get; set; }
    }
}
