//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class toCypro
    {
        public int tcId { get; set; }
        public decimal tcPacId { get; set; }
        public Nullable<decimal> tcBolId { get; set; }
        public Nullable<decimal> tcKPId { get; set; }
        public string tcStatus { get; set; }
        public string hl7Sent { get; set; }
        public string hl7Ack { get; set; }
        public Nullable<System.DateTime> tcCreatedDate { get; set; }
        public Nullable<System.DateTime> tcSentDate { get; set; }
        public string tcEvent { get; set; }
    
        public virtual BolnichnoLechenie BolnichnoLechenie { get; set; }
        public virtual KpLechenie KpLechenie { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
