//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToLIS
    {
        public decimal TLId { get; set; }
        public System.DateTime TLData { get; set; }
        public decimal TLNaznId { get; set; }
        public string TLNaznVid { get; set; }
        public decimal TLPacId { get; set; }
        public string TLPacEGN { get; set; }
        public string TLHA { get; set; }
        public Nullable<decimal> TLBolId { get; set; }
        public string TLIZNo { get; set; }
        public string TLStatus { get; set; }
        public Nullable<decimal> TLNLekar { get; set; }
        public bool TLNSpeshno { get; set; }
        public string TLNVid { get; set; }
        public Nullable<decimal> TLNVidMKB { get; set; }
        public string TLNDop { get; set; }
        public decimal TLNOtZveno { get; set; }
        public decimal TLNVZveno { get; set; }
        public decimal TLNDiag { get; set; }
        public System.DateTime TLNIzp { get; set; }
        public decimal TLNKamOtceta { get; set; }
        public decimal TLNIztFin { get; set; }
        public Nullable<System.DateTime> TLDataVzMat { get; set; }
        public string TLStaia { get; set; }
        public string TLLeglo { get; set; }
        public int attempts { get; set; }
        public string hl7Sent { get; set; }
        public string hl7Ack { get; set; }
    }
}
