//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToPACS
    {
        public decimal TPId { get; set; }
        public System.DateTime TPData { get; set; }
        public decimal TPNaznId { get; set; }
        public string TPNaznVid { get; set; }
        public string TPNaznTip { get; set; }
        public decimal TPPacId { get; set; }
        public string TPPacEGN { get; set; }
        public string TPHA { get; set; }
        public Nullable<decimal> TPBolId { get; set; }
        public string TPIZNo { get; set; }
        public string TPStatus { get; set; }
        public Nullable<decimal> TPNLekar { get; set; }
        public bool TPNSpeshno { get; set; }
        public Nullable<decimal> TPNVid { get; set; }
        public Nullable<decimal> TPNVidMKB { get; set; }
        public string TPNDop { get; set; }
        public decimal TPNOtZveno { get; set; }
        public decimal TPNVZveno { get; set; }
        public decimal TPNDiag { get; set; }
        public System.DateTime TPNIzp { get; set; }
        public string TPNObsUch { get; set; }
        public string TPModality { get; set; }
    }
}
