//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToSMOBZ
    {
        public decimal TSId { get; set; }
        public System.DateTime TSData { get; set; }
        public decimal TSPacId { get; set; }
        public decimal TSBolId { get; set; }
        public string TSPacEGN { get; set; }
        public string TSIZNo { get; set; }
        public string TSStatus { get; set; }
    }
}
