//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraceLog
    {
        public System.DateTime CREATED_DATE { get; set; }
        public int SEVERITY { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string CATEGORY { get; set; }
        public string VALUE { get; set; }
        public int id { get; set; }
    }
}
