//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferKDKK_3
    {
        public decimal ID3 { get; set; }
        public string D_ZUZ { get; set; }
        public string PacObrazovanie { get; set; }
    }
}
