//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trudozaguba
    {
        public decimal ID { get; set; }
        public decimal LID { get; set; }
        public Nullable<decimal> TrVid { get; set; }
        public decimal TrBroDni { get; set; }
    
        public virtual BList BList { get; set; }
        public virtual Nomenklatura Nomenklatura { get; set; }
    }
}
