//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UslugaGrupa
    {
        public decimal UslGrID { get; set; }
        public decimal UslGrUsluga { get; set; }
        public decimal UslGrGrupa { get; set; }
        public string UslGrRes { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
