//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCentur
    {
        public decimal BolnicaID { get; set; }
        public Nullable<decimal> BolRegNomer { get; set; }
        public string BolIme { get; set; }
        public Nullable<System.DateTime> MCDoData { get; set; }
    }
}
