//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFacCentur
    {
        public decimal ID { get; set; }
        public Nullable<decimal> RegNomer { get; set; }
        public string Ime { get; set; }
        public string Adres { get; set; }
        public string DanNomer { get; set; }
        public string Bulstat { get; set; }
        public string MOL { get; set; }
        public string BankaIme { get; set; }
        public string BIC { get; set; }
        public string IBAN { get; set; }
        public Nullable<decimal> NachNO { get; set; }
        public Nullable<decimal> KrNo { get; set; }
        public decimal Kontragent { get; set; }
    }
}
