//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWXLS
    {
        public System.DateTime ProDataChas { get; set; }
        public string PersUIN { get; set; }
        public string DiagKod { get; set; }
        public string PacEGN { get; set; }
        public string PacIme { get; set; }
        public string NasNoNapr { get; set; }
        public Nullable<System.DateTime> NasOtData { get; set; }
        public string NasNoZZ { get; set; }
        public string NasUINLekar { get; set; }
        public string SpecPersKod { get; set; }
        public string UslugaMKB { get; set; }
        public string UslugaKod { get; set; }
        public bool ProAmbList { get; set; }
        public decimal AmbListNo { get; set; }
        public System.DateTime Datata { get; set; }
    }
}
