//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGettAllProc
    {
        public Nullable<decimal> ProMKB { get; set; }
        public string ProcVid { get; set; }
        public string ProcVidDii { get; set; }
        public string ProcVidEfi { get; set; }
        public string ProcVidIP { get; set; }
        public Nullable<decimal> BolID { get; set; }
        public string BLIZNo { get; set; }
        public Nullable<decimal> aaa { get; set; }
        public Nullable<decimal> bbb { get; set; }
        public Nullable<decimal> ccc { get; set; }
        public Nullable<decimal> ddd { get; set; }
        public Nullable<decimal> EfiMKB { get; set; }
        public Nullable<decimal> IpMKB { get; set; }
        public decimal BLPacID { get; set; }
    }
}
