//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewImpStoinost
    {
        public Nullable<decimal> BolId { get; set; }
        public decimal KPIid { get; set; }
        public Nullable<decimal> ImpVid { get; set; }
        public decimal ImplantantID { get; set; }
        public string ImplVid { get; set; }
        public string ImpFirma { get; set; }
        public System.DateTime ImpData { get; set; }
        public string ImpFabNo { get; set; }
        public string ImpTargovsko { get; set; }
        public string ImpKatNomer { get; set; }
        public string ImpProizvoditel { get; set; }
        public string ImpFakNo { get; set; }
        public Nullable<System.DateTime> ImpFakData { get; set; }
        public decimal ImpDopZap { get; set; }
        public Nullable<decimal> EventID { get; set; }
        public int EventVid { get; set; }
        public Nullable<bool> ImpZapNZOK { get; set; }
        public Nullable<decimal> OperaciaID { get; set; }
        public Nullable<decimal> ProID { get; set; }
        public Nullable<decimal> DiiID { get; set; }
        public Nullable<decimal> IpID { get; set; }
        public Nullable<decimal> EfiID { get; set; }
        public Nullable<decimal> ImpCenaNZOK { get; set; }
        public string ImpCodeNZOK { get; set; }
        public Nullable<bool> ImpSistema { get; set; }
        public Nullable<decimal> ImpProc { get; set; }
        public Nullable<decimal> ImpStoinost { get; set; }
        public string ImpDealer { get; set; }
        public Nullable<decimal> ImpFakStoinost { get; set; }
        public string ImpSklNo { get; set; }
    }
}
