//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPK011
    {
        public string BLIZNo { get; set; }
        public string Expr1 { get; set; }
        public string PacEGN { get; set; }
        public Nullable<int> KpKproCount { get; set; }
        public Nullable<int> LegloDni { get; set; }
        public string KlinPatKod { get; set; }
        public int KlinPatMinPrestoiCheck { get; set; }
        public bool HasSecondDiag { get; set; }
        public string NomIme { get; set; }
    }
}
