//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View3
    {
        public decimal NomenklaturaID { get; set; }
        public Nullable<decimal> NomenklaturaSelfID { get; set; }
        public string NomIme { get; set; }
        public string NNomIme { get; set; }
        public Nullable<decimal> NNID { get; set; }
    }
}
