//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIntPrev
    {
        public Nullable<decimal> PrevejdaneID { get; set; }
        public decimal BolID { get; set; }
        public decimal PrevMiasto { get; set; }
        public decimal BLPacID { get; set; }
        public string BLIZNo { get; set; }
        public System.DateTime OtData { get; set; }
        public Nullable<System.DateTime> DoData { get; set; }
    }
}
