//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewToCypro
    {
        public int tcId { get; set; }
        public decimal tcPacid { get; set; }
        public string tcStatus { get; set; }
        public string tcEvent { get; set; }
        public string PacIme { get; set; }
        public string PacPrezime { get; set; }
        public string PacFamilia { get; set; }
        public string PacGrad { get; set; }
        public string PacAdres { get; set; }
        public System.DateTime PacDataNaRajdane { get; set; }
        public bool PacIsJena { get; set; }
        public string PacEGN { get; set; }
        public bool PacIsEnCh { get; set; }
        public string tcPersIme { get; set; }
        public string tcPersUIN { get; set; }
        public string tcZvenoKod { get; set; }
        public string tcZvenoIme { get; set; }
        public string tcRoom { get; set; }
        public string tcBed { get; set; }
        public string tcPatientClass { get; set; }
        public Nullable<System.DateTime> tcDataChas { get; set; }
        public string tcBLIZNo { get; set; }
        public Nullable<decimal> tcHospitalID { get; set; }
    }
}
