//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLechebniZavedenia
    {
        public decimal Id { get; set; }
        public Nullable<decimal> RegNomer { get; set; }
        public string Ime { get; set; }
        public string Oblast { get; set; }
        public string Obshtina { get; set; }
        public string Adres { get; set; }
        public string BankaIme { get; set; }
        public string BankaKod { get; set; }
        public string BankaSmetka { get; set; }
        public string Bulstat { get; set; }
        public string DanNomer { get; set; }
        public Nullable<decimal> RZOK { get; set; }
        public string Prov1 { get; set; }
        public string Prov2 { get; set; }
        public string Mol { get; set; }
        public string MolEGN { get; set; }
        public string MolUIN { get; set; }
        public string FarmUIN { get; set; }
    }
}
