//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDiagProc
    {
        public System.DateTime ProDataChas { get; set; }
        public bool ProSpeshno { get; set; }
        public decimal ProMiasto { get; set; }
        public Nullable<decimal> ProMKB { get; set; }
        public Nullable<decimal> ProDiag { get; set; }
        public string ProZak { get; set; }
        public Nullable<decimal> BolId { get; set; }
    }
}
