//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGetAllOper
    {
        public decimal OperaciaID { get; set; }
        public decimal OperLecProc1 { get; set; }
        public string BLIZNo { get; set; }
        public decimal BLPacID { get; set; }
        public decimal ID { get; set; }
        public string OperVid { get; set; }
    }
}
