//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewLkk
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> LKKType { get; set; }
        public decimal DoctorID { get; set; }
        public decimal DoctorId1 { get; set; }
        public Nullable<decimal> DoctorId2 { get; set; }
        public string Doctor1Name { get; set; }
        public string Doctor2Name { get; set; }
        public string Doctor3Name { get; set; }
        public string Doctor1UIN { get; set; }
        public string Doctor2UIN { get; set; }
        public string Doctor3UIN { get; set; }
    }
}
