//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View8
    {
        public decimal PregledID { get; set; }
        public decimal PacientID { get; set; }
        public decimal PregledMiasto { get; set; }
        public decimal PregledLekar { get; set; }
        public decimal MC { get; set; }
        public System.DateTime PregledData { get; set; }
        public string FULLNAME { get; set; }
        public string PacEGN { get; set; }
        public string ZvenoIme { get; set; }
        public string Lekar { get; set; }
        public string MCIme { get; set; }
        public string RZOK { get; set; }
        public string ZR { get; set; }
        public string PacGrad { get; set; }
        public string PacAdres { get; set; }
    }
}
