//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPersonalNames
    {
        public decimal PersonalID { get; set; }
        public decimal SpecialnostPersonalID { get; set; }
        public Nullable<decimal> ZvenoID { get; set; }
        public bool PersIsLekar { get; set; }
        public string PersEGN { get; set; }
        public string PersIme { get; set; }
        public string PersZvanie { get; set; }
        public bool PersIsInvisible { get; set; }
        public Nullable<System.DateTime> PersDoData { get; set; }
        public string PersUIN { get; set; }
        public Nullable<decimal> PersSimp { get; set; }
        public bool PersIsMC { get; set; }
        public bool PersIsENC { get; set; }
        public bool PersIsSpecializant { get; set; }
        public decimal PersNNAl { get; set; }
        public decimal PersNNDd { get; set; }
        public decimal PersNNN3 { get; set; }
        public decimal PersNNN3A { get; set; }
        public decimal PersNNN4 { get; set; }
        public decimal PersNNN6 { get; set; }
        public Nullable<decimal> PersNNRec { get; set; }
        public string PersTel { get; set; }
        public Nullable<bool> PersNachKlinika { get; set; }
        public string TITLE { get; set; }
        public string FULL_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
    }
}
