//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewToLis
    {
        public decimal TLId { get; set; }
        public System.DateTime TLData { get; set; }
        public decimal TLNaznId { get; set; }
        public string TLNaznVid { get; set; }
        public decimal TLPacId { get; set; }
        public string TLPacEGN { get; set; }
        public string TLHA { get; set; }
        public Nullable<decimal> TLBolId { get; set; }
        public string TLIZNo { get; set; }
        public string TLStatus { get; set; }
        public Nullable<decimal> TLNLekar { get; set; }
        public bool TLNSpeshno { get; set; }
        public string TLNVid { get; set; }
        public Nullable<decimal> TLNVidMKB { get; set; }
        public string TLNDop { get; set; }
        public decimal TLNDiag { get; set; }
        public System.DateTime TLNIzp { get; set; }
        public decimal TLNKamOtceta { get; set; }
        public decimal TLNIztFin { get; set; }
        public string TLStaia { get; set; }
        public string TLLeglo { get; set; }
        public int attempts { get; set; }
        public string PacIme { get; set; }
        public string PacPrezime { get; set; }
        public string PacFamilia { get; set; }
        public System.DateTime PacDataNaRajdane { get; set; }
        public bool PacIsJena { get; set; }
        public string ZvenoKod { get; set; }
        public string ZvenoIme { get; set; }
        public string PersUIN { get; set; }
        public string PersIme { get; set; }
        public string PersUIN1 { get; set; }
        public string PersIme1 { get; set; }
        public Nullable<System.DateTime> BLDataChas { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<System.DateTime> OrdEDataMat { get; set; }
        public Nullable<decimal> NomenklaturaID { get; set; }
        public string NomIme { get; set; }
        public string ZvenoKod1 { get; set; }
        public string ZvenoIme1 { get; set; }
        public string DiagKod { get; set; }
        public string DiagIme { get; set; }
        public string PacGrad { get; set; }
        public string PacAdres { get; set; }
        public string ProcName { get; set; }
        public bool PacIsENCh { get; set; }
        public Nullable<int> BLIsSpeshen { get; set; }
    }
}
