//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrpRegJournal
    {
        public string FULLNAME { get; set; }
        public bool PacIsVavJurnal { get; set; }
        public string MiastoReg { get; set; }
        public string Darjava { get; set; }
        public string Grajdanstvo { get; set; }
        public string PacEGN { get; set; }
        public string PacJurnalenNomer { get; set; }
        public System.DateTime PacDataNaRegistracia { get; set; }
        public string Age { get; set; }
    }
}
