//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUslojIOcenki
    {
        public Nullable<int> UOsnZab { get; set; }
        public Nullable<int> UPridZab { get; set; }
        public Nullable<int> ULecDiag { get; set; }
        public Nullable<int> UOrgOtk { get; set; }
        public Nullable<int> UVunObst { get; set; }
        public Nullable<int> ULetIzhod { get; set; }
        public Nullable<short> OcIzpKP { get; set; }
        public Nullable<short> OcBolPres { get; set; }
        public Nullable<short> OcBolSmurt { get; set; }
        public Nullable<short> OcSuvpDiag { get; set; }
        public decimal BolID { get; set; }
        public decimal PacientID { get; set; }
    }
}
