//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransferKR
    {
        public string Пациент_Име { get; set; }
        public string ИЗNo { get; set; }
        public decimal Статус { get; set; }
        public System.DateTime Заявен_трансфер { get; set; }
        public Nullable<System.DateTime> Изпълнен_трансфер { get; set; }
    }
}
