//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransferZvena
    {
        public Nullable<System.DateTime> От_дата { get; set; }
        public Nullable<System.DateTime> До_дата { get; set; }
        public System.DateTime Изпълнен_трансфер { get; set; }
    }
}
