//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightedCalculationByEventAndUnit
    {
        public decimal id { get; set; }
        public decimal razhodiid { get; set; }
        public decimal zvenoid { get; set; }
        public Nullable<decimal> razhodtipid { get; set; }
        public double WeightedCount { get; set; }
        public Nullable<decimal> AvaragePrice { get; set; }
    
        public virtual Razhodi Razhodi { get; set; }
        public virtual RazhodTip RazhodTip { get; set; }
        public virtual Zveno Zveno { get; set; }
    }
}
