//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_Param
    {
        public decimal id { get; set; }
        public string CompName { get; set; }
        public Nullable<decimal> valLabMesto { get; set; }
        public Nullable<decimal> valRodMesto { get; set; }
        public Nullable<decimal> valFniMesto { get; set; }
        public Nullable<decimal> valDiiMesto { get; set; }
        public Nullable<decimal> valIpMesto { get; set; }
        public Nullable<decimal> valEfiMesto { get; set; }
        public Nullable<decimal> valProMesto { get; set; }
        public Nullable<decimal> valVsiMesto { get; set; }
        public Nullable<decimal> valHemMesto { get; set; }
        public Nullable<decimal> valObsMesto { get; set; }
        public Nullable<decimal> valOrderPRO { get; set; }
        public Nullable<decimal> valOrderLAB { get; set; }
        public Nullable<decimal> valOrderFNI { get; set; }
        public Nullable<decimal> valOrderROD { get; set; }
        public Nullable<decimal> valOrderMED { get; set; }
        public Nullable<decimal> valMdiMesto { get; set; }
    }
}
