//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xc001helper
    {
        public Nullable<decimal> bolId { get; set; }
        public string impTargovsko { get; set; }
        public System.DateTime impdata { get; set; }
        public Nullable<decimal> impproc { get; set; }
        public Nullable<decimal> EventZvenoID { get; set; }
        public Nullable<decimal> factura { get; set; }
        public Nullable<decimal> pacient { get; set; }
        public Nullable<decimal> nzok { get; set; }
    }
}
