//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlPatient
    {
        public decimal PacientID { get; set; }
        public string EGN { get; set; }
        public bool PacIsENCh { get; set; }
        public bool PacZOES { get; set; }
        public System.DateTime dateBirth { get; set; }
        public int Sex { get; set; }
        public string SS_No { get; set; }
        public string COUNTRYCODE { get; set; }
        public string COUNTRYIDNO { get; set; }
        public string Type_CERTIFICATE { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string PacOOIme { get; set; }
        public string PacOsiguren { get; set; }
        public string EHIC_No { get; set; }
        public string PersID_No { get; set; }
        public string patientBranch { get; set; }
        public string patientHRegion { get; set; }
        public string Given { get; set; }
        public string Sur { get; set; }
        public string Family { get; set; }
        public string Address { get; set; }
        public int PacType { get; set; }
        public string PacFullName { get; set; }
    }
}
