<?php  /** @var \ShoppingCart\ViewModels\RegisterInformation $model */ ?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script>function toggleSearch() {
            var searchDiv = document.getElementById("search-block");
            searchDiv.className = searchDiv.className == "show" ? "" : "show";}
    </script>
</head>
<body style="padding:20px 6px;margin:0;">

<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>
<div>
    <h1><?= $model->error ? $model->error : ''; ?></h1>
</div>

<h1>Register form</h1>
<div>
    <?=
    \ShoppingCart\Helpers\FormViewHelper::init()
        ->initForm()
            ->setAttribute('action', \ShoppingCart\Helpers\HelpFunctions::url() . "users/register/post")
            ->setAttribute('method', 'post')
            ->create()
        ->initLabel()
            ->setAttribute('for', 'username')
            ->setContent('User name: ')
            ->create()
        ->initTextBox()
            ->setName('username')
            ->setAttribute('id', 'username')
            ->setAttribute('required', 'true')
            ->setNewLine()
            ->create()
        ->initLabel()
            ->setAttribute('for', 'password')
            ->setContent('Password: ')
            ->create()
        ->initPasswordBox()
            ->setName('password')
            ->setAttribute('id', 'password')
            ->setAttribute('required', 'true')
            ->setNewLine()
            ->create()
        ->initLabel()
            ->setAttribute('for', 'confPassword')
            ->setContent('Confirm password: ')
            ->create()
        ->initPasswordBox()
            ->setName('confPassword')
            ->setAttribute('id', 'confPassword')
            ->setAttribute('required', 'true')
            ->setNewLine()
            ->create()
        ->initLabel()
            ->setAttribute('for', 'email')
            ->setContent('Email: ')
            ->create()
        ->initEmailBox()
            ->setName('email')
            ->setAttribute('id', 'email')
            ->setAttribute('required', 'true')
            ->setNewLine()
            ->create()

        ->initLabel()
            ->setAttribute('for', 'cash')
            ->setContent('Cash: ')
            ->create()
        ->initNumberBox()
            ->setName('cash')
            ->setAttribute('id', 'cash')
            ->setAttribute('min', '1')
            ->setAttribute('max', '15000')
            ->setNewLine()
            ->create()
        ->initSubmit()
            ->setValue('Register')
            ->setNewLine()
            ->create()
        ->render();
    ?>
</div>

<div>
    <?php echo \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'login', [], '[Login]')?>
</div>


</body>
</html>