<?php  /** @var \ShoppingCart\Models\User $model */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/accordionmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/accordionmenu.js" type="text/javascript"></script>
<!--    <script>function toggleSearch() {-->
<!--            var searchDiv = document.getElementById("search-block");-->
<!--            searchDiv.className = searchDiv.className == "show" ? "" : "show";}-->
<!--    </script>-->
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
</head>
<body style="padding:20px 6px;margin:0;">


<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>



<main>

    <?php echo \ShoppingCart\Helpers\Partials\PartialAside::create()?>

    <div class="wrapper">
        <?= $model->isError() ? $model->isError() : ''; ?>
        <?= $model->isSuccess() ? $model->isSuccess() : ''; ?>
        <h1>Hello, <?= htmlspecialchars($model->getUsername()); ?></h1>

        <h3>
            Profile Info:
            <p>Email: <?= $model->getEmail(); ?></p>
            <p>Cash: <?= $model->getCash(); ?></p>
        </h3>

        <div>
            <?=
             \ShoppingCart\Helpers\FormViewHelper::init()
                ->initTextBox()
                ->setName('username')
                ->setValue('pesho')
                ->setAttribute('class', 'field-green')
                ->create()
                ->initPasswordBox()
                ->setName('password')
                ->setAttribute('id', 'input-pass')
                ->create()
                ->render();
            ?>
        </div>

        <div>
            <?= \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
        </div>

        <div>

            <?php


            ?>

        </div>


    </div>
</main>







</body>
</html>