-- MySQL Workbench Synchronization
-- Generated: 2015-06-24 14:14
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: isrmn

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `typical_uni`.`Students` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ID`)  COMMENT '';

ALTER TABLE `typical_uni`.`Courses` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ID`)  COMMENT '';

ALTER TABLE `typical_uni`.`Departments` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ID`)  COMMENT '';

ALTER TABLE `typical_uni`.`Professors` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ID`)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
