//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftUni_Console_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursOldDataCommand
    {
        public Nullable<int> OldDataID { get; set; }
        public int CommandID { get; set; }
        public Nullable<int> NewDataID { get; set; }
        public System.DateTime ChageDataTime { get; set; }
        public string Reason { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual WorkHoursOldData WorkHoursOldData { get; set; }
    }
}
