<?= $model->error ? $model->error : ''; ?>
<?= $model->success ? $model->success : ''; ?>
<h1>Buildings for <?= htmlspecialchars($model->username); ?></h1>

<h3>
    Resources:
    <p>Gold: <?= $model->gold; ?></p>
    <p>Food: <?= $model->food; ?></p>
</h3>

<?php echo \SoftUni\Helpers\HelpFunctions::createBuildingsTable($model->buildings, true)?>
<div>
    <?php echo \SoftUni\Helpers\HelpFunctions::anchor('users', 'profile', [] ,'[Back to profile]')?>
</div>
<div><br>
    <?php echo \SoftUni\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
</div>