<?php  /** @var \ShoppingCart\Models\User $model */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/accordionmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/accordionmenu.js" type="text/javascript"></script>

    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
</head>
<body style="padding:20px 6px;margin:0;">


<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>



<main>

    <?php echo \ShoppingCart\Helpers\Partials\PartialAside::create()?>

    <div class="wrapper">
        <?= $model->isError() ? $model->isError() : ''; ?>
        <?= $model->isSuccess() ? $model->isSuccess() : ''; ?>
        <h1>Hello, <?= htmlspecialchars($model->getUsername()); ?></h1>

        <h3>
            Profile Info:
            <p>Email: <?= $model->getEmail(); ?></p>
            <p>Cash: <?= $model->getCash(); ?></p>
        </h3>


        <div>
            <?php
                $token = htmlspecialchars($_SESSION['formToken']);
                $username = htmlspecialchars($model->getUsername());
                $email =  htmlspecialchars($model->getEmail());
            ?>

            <?=
            \ShoppingCart\Helpers\FormViewHelper::init()
                ->initForm()
                    ->setAttribute('action', '')
                    ->setAttribute('method', 'post')
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'username')
                    ->setContent('User name: ')
                    ->create()
                ->initTextBox()
                    ->setName('username')
                    ->setAttribute('id', 'username')
                    ->setAttribute('value', "{$username}")
                    ->setNewLine()
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'new-username')
                    ->setContent('New username: ')
                    ->create()
                ->initTextBox()
                    ->setName('new-username')
                    ->setAttribute('id', 'new-username')
                    ->setAttribute('placeholder', "enter new user name")
                    ->setNewLine()
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'confirm-username')
                    ->setContent('Confirm username: ')
                    ->create()
                ->initTextBox()
                    ->setName('confirm-username')
                    ->setAttribute('id', 'confirm-username')
                    ->setAttribute('placeholder', "confirm new user name")
                    ->setNewLine()
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'email')
                    ->setContent('Email: ')
                    ->create()
                ->initTextBox()
                    ->setName('email')
                    ->setAttribute('id', 'email')
                    ->setAttribute('value', "{$email}")
                    ->setNewLine()
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'new-email')
                    ->setContent('New email: ')
                    ->create()
                ->initEmailBox()
                    ->setName('new-email')
                    ->setAttribute('id', 'new-email')
                    ->setAttribute('placeholder', "enter new email")
                    ->setNewLine()
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'confirm-email')
                    ->setContent('Confirm new email: ')
                    ->create()
                ->initEmailBox()
                    ->setName('confirm-email')
                    ->setAttribute('id', 'confirm-email')
                    ->setAttribute('placeholder', "confirm new email")
                    ->setNewLine()
                    ->create()
                ->initSubmit()
                    ->setName('edit')
                    ->setValue('Edit')
                    ->setNewLine()
                    ->create()
                ->initHiddenBox()
                    ->setName('formToken')
                    ->setAttribute('value', "{$token}")
                    ->setNewLine()
                    ->create()
                ->render();
            ?>

        </div>

        <div>
            <?php echo \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
        </div>
    </div>


</main>

</body>
</html>