<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.js" type="text/javascript"></script>
    <script>function toggleSearch() {
            var searchDiv = document.getElementById("search-block");
            searchDiv.className = searchDiv.className == "show" ? "" : "show";}
    </script>
</head>
<body style="padding:20px 6px;margin:0;">

<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>

<?= $model->error ? $model->error : ''; ?>
<h1>Login form</h1>
<form action="" method="post">
    <label for="username">User name: </label>
    <input type="text" name="username" id="username" required="true"/><br>
    <label for="password">Password: </label>
    <input type="password" name="password" id="password" required="true"/><br>
    <input type="submit" value="Login"/>
</form>
<div>
    <?php echo \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'register', [], '[Register]')?>
</div>

</body>
</html>