

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.js" type="text/javascript"></script>
    <script>function toggleSearch() {
            var searchDiv = document.getElementById("search-block");
            searchDiv.className = searchDiv.className == "show" ? "" : "show";}
    </script>
</head>
<body style="padding:20px 6px;margin:0;">

<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>

<?= $model->getError() ? $model->getError() : ''; ?>
<?= $model->getSuccess() ? $model->getSuccess() : ''; ?>
<h1>Hello, <?= htmlspecialchars($model->getUsername()); ?></h1>

<h3>
    Profile Info:
    <p>Email: <?= $model->getEmail(); ?></p>
    <p>Cash: <?= $model->getCash(); ?></p>
</h3>

<div>



    <?php

    $array = $_SESSION['nestedCategories'];
    $tempArray = [];
    foreach($array as $value){
        $root_name = $value['root_name'];
        $down1_name = $value['down1_name'];
        $down2_name = $value['down2_name'];
        $down3_name = $value['down3_name'];

        if(empty($root_name)){
            continue;
        }
        if(!array_key_exists($root_name, $tempArray)){
            $tempArray[$root_name] = array();
        }


        if(empty($down1_name)){
            continue;
        }
        if(!array_key_exists($down1_name, $tempArray[$root_name])){
            $tempArray[$root_name][$down1_name] = array();

        }

        if(empty($down2_name)){
            continue;
        }
        if(!array_key_exists($down2_name, $tempArray[$root_name][$down1_name])){
            $tempArray[$root_name][$down1_name][$down2_name] = array();

        }

        if(empty($down3_name)){
            continue;
        }

        if(!array_key_exists($down3_name, $tempArray[$root_name][$down1_name][$down2_name])){
            $tempArray[$root_name][$down1_name][$down2_name][$down3_name] = array();
        }
    }

var_dump($tempArray);
    var_dump($array);
    ?>
</div>
<div>
    <?php var_dump($_SESSION['categories'])?>
</div>


<div>
    <?php echo \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
</div>


</body>
</html>