<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script>function toggleSearch() {
            var searchDiv = document.getElementById("search-block");
            searchDiv.className = searchDiv.className == "show" ? "" : "show";}
    </script>
</head>
<body style="padding:20px 6px;margin:0;">

<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>

<h1>Register form</h1>
<form action="" method="post">
    <label for="username">User name: </label>
    <input type="text" name="username" id="username" required="true"/><br>
    <label for="password">Password: </label>
    <input type="password" name="password" id="password" required="true"/><br>
    <label for="conf-password">Confirm password: </label>
    <input type="password" name="conf-password" id="conf-password" required="true"/><br>
    <label for="email">Email: </label>
    <input type="email" name = "email" id="email" required="true"/><br>
    <label for="cash">Cash: </label>
    <input type="number"name="cash" id="cash" min="1" max="15000"/><br>
    <input type="submit" value="Register"/>
</form>

<div>
    <?php echo \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'login', [], '[Login]')?>
</div>


</body>
</html>