<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/accordionmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/accordionmenu.js" type="text/javascript"></script>

    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
</head>
<body style="padding:20px 6px;margin:0;">


<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>



<main>

    <div class="wrapper">
        <?= $model->getError() ? $model->getError() : ''; ?>
        <?= $model->getSuccess() ? $model->getSuccess() : ''; ?>
        <h1>Hello, <?= htmlspecialchars($model->getUsername()); ?></h1>

        <h3>
            Profile Info:
            <p>Email: <?= $model->getEmail(); ?></p>
            <p>Cash: <?= $model->getCash(); ?></p>
        </h3>

        <form action="" method="post">
            <div>
                <h1><?= ucfirst(htmlspecialchars($model->getUsername())); ?>, are you sure you want to delete your profile?</h1>
                <label for="password">Password: </label>
                <input type="password" id="password" name="password" placeholder="enter new password" "/>
                <input type="submit" name="delete" value="Delete"/>
                <input type="hidden" name="formToken" value="<?= htmlspecialchars($_SESSION['formToken'])?>">
            </div>
        </form>

        <div>
            <?php echo \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
        </div>
    </div>


</main>

</body>
</html>