<?php  /** @var \ShoppingCart\Models\User $model */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/accordionmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/accordionmenu.js" type="text/javascript"></script>

    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
</head>
<body style="padding:20px 6px;margin:0;">


<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>



<main>

    <?php echo \ShoppingCart\Helpers\Partials\PartialAside::create()?>

    <div class="wrapper">
        <?= $model->isError() ? $model->isError() : ''; ?>
        <?= $model->isSuccess() ? $model->isSuccess() : ''; ?>
        <h1>Hello, <?= htmlspecialchars($model->getUsername()); ?></h1>

        <h3>
            Profile Info:
            <p>Email: <?= $model->getEmail(); ?></p>
            <p>Cash: <?= $model->getCash(); ?></p>
        </h3>


        <div>
            <form action="" method="post">
                <div>
                    <div>
                        <label for="username">Username: </label>
                        <input type="text" id="username" name="username" value="<?= htmlspecialchars($model->getUsername()); ?>"/>
                        <label for="new-username">New username: </label>
                        <input type="text" id="new-username" name="new-username" placeholder="enter new user name"/>
                        <label for="confirm-username">Confirm username: </label>
                        <input type="text" id="confirm-username" name="confirm-username" placeholder="confirm new user name"/>
                    </div>
                    <div>
                        <label for="email">Email: </label>
                        <input type="text" id="email" name="email" value="<?= htmlspecialchars($model->getEmail()); ?>"/>
                        <label for="new-email">New email: </label>
                        <input type="text" id="new-email" name="new-email" placeholder="enter new email"/>
                        <label for="confirm-email">Confirm new email: </label>
                        <input type="text" id="confirm-email" name="confirm-email" placeholder="confirm new email"/>
                    </div>
<!--                    <div>-->
<!--                        <label for="password">Change Password: </label>-->
<!--                        <input type="password" id="password" name="password" placeholder="enter new password" "/>-->
<!--                        <label for="confirm-password">Confirm password: </label>-->
<!--                        <input type="password" id="confirm-password" name="confirm-password" placeholder="confirm new password"/>-->
<!--                    </div>-->
                    <div>
                        <input type="submit" name="edit" value="Edit"/>
                        <input type="hidden" name="formToken" value="<?= htmlspecialchars($_SESSION['formToken'])?>">
                    </div>
                </div>
            </form>
        </div>


        <?=

        \ShoppingCart\Helpers\FormViewHelper::init()
            ->initTextBox()
                ->setName('username')
                ->setValue('pesho')
                ->setAttribute('class', 'field-green')
                ->create()
            ->initPasswordBox()
                ->setName('password')
                ->setAttribute('id', 'input-pass')
                ->create()
            ->render();
        ?>

        <div>
            <?php echo \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
        </div>
    </div>


</main>

</body>
</html>