//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftUniContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursOldData
    {
        public WorkHoursOldData()
        {
            this.WorkHoursOldDataCommands = new HashSet<WorkHoursOldDataCommand>();
        }
    
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime TaskDate { get; set; }
        public string Task { get; set; }
        public int WorkHours { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<WorkHoursOldDataCommand> WorkHoursOldDataCommands { get; set; }
    }
}
