<?php  /** @var \ShoppingCart\ViewModels\CategoriesViewModel $model */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/accordionmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/accordionmenu.js" type="text/javascript"></script>
    <!--    <script>function toggleSearch() {-->
    <!--            var searchDiv = document.getElementById("search-block");-->
    <!--            searchDiv.className = searchDiv.className == "show" ? "" : "show";}-->
    <!--    </script>-->
    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <!--    <script> amenu.open("li22", false); amenu.open("li31", false); </script>-->
</head>
<body style="padding:20px 6px;margin:0;">


<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>



<main>

    <?php echo \ShoppingCart\Helpers\Partials\PartialAside::create()?>

    <div class="wrapper">
        <?= $model->isError() ? $model->isError() : ''; ?>
        <?= $model->isSuccess() ? $model->isSuccess() : ''; ?>
        <h1>List categories</h1>

        <div >
            <?= \ShoppingCart\Helpers\DropDownHelper::create()
                ->setDefaultOption("Categories")
                ->render();





//            ?>
        </div>

        <div>
            <?= \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
        </div>

        <div>


        </div>


    </div>
</main>


</body>
</html>