<?php  /** @var \ShoppingCart\ViewModels\CategoriesViewModel $model */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/ddmenu.css" type="text/css" />
    <link rel="stylesheet" href="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>Styles/accordionmenu.css" type="text/css" />
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/ddmenu.js" type="text/javascript"></script>
    <script src="<?=\ShoppingCart\Helpers\HelpFunctions::url()?>JS/accordionmenu.js" type="text/javascript"></script>
    <!--    <script>function toggleSearch() {-->
    <!--            var searchDiv = document.getElementById("search-block");-->
    <!--            searchDiv.className = searchDiv.className == "show" ? "" : "show";}-->
    <!--    </script>-->
    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(false); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <script> amenu.close(); </script>
    <!--    <script> amenu.open("li22", false); amenu.open("li31", false); </script>-->
</head>
<body style="padding:20px 6px;margin:0;">


<?php echo \ShoppingCart\Helpers\Partials\PartialHeader::create()?>



<main>

    <?php echo \ShoppingCart\Helpers\Partials\PartialAside::create()?>

    <div class="wrapper">
        <?= $model->isError() ? $model->isError() : ''; ?>
        <?= $model->isSuccess() ? $model->isSuccess() : ''; ?>
        <?= isset($_GET) ? reset($_GET) : ''?>
        <h1>Add product category</h1>
        <?php
        ?>

        <?php $selectCode = \ShoppingCart\Helpers\DropDownHelper::create()
            ->addAttribute('name', 'parentid')
            ->addAttribute('id', 'parentid')
            ->setContent($model->getCategories(), 'id', 'name', 'name')
            ->setDefaultOption("--Categories--")
            ->render(); ?>


        <div ><span><strong>Existing categories:  </strong></span>
            <?= $selectCode ?>
        </div>
        </br>



        <div>
            <?=
            \ShoppingCart\Helpers\FormViewHelper::init()
                ->initForm()
                    ->setAttribute('action', \ShoppingCart\Helpers\HelpFunctions::url() . "categories/add/post")
                    ->setAttribute('method', 'post')
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'categoryname')
                    ->setContent('Category name: ')
                    ->create()
                ->initTextBox()
                    ->setName('categoryname')
                    ->setAttribute('id', 'categoryname')
                    ->setAttribute('required', 'true')
                    ->setNewLine()
                    ->create()
                ->initLabel()
                    ->setAttribute('for', 'categories')
                    ->setContent('Parent name: ')
                    ->create()
                ->insertIntoForm("{$selectCode}")

                ->initSubmit()
                ->setValue('Add')
                ->setNewLine()
                ->create()
                ->render();
            ?>
        </div>


        <div>
            <?= \ShoppingCart\Helpers\HelpFunctions::anchor('users', 'logout', [], '[Logout]')?>
        </div>

        <div>


        </div>


    </div>
</main>


</body>
</html>